# 🚀 LAB GUIDE — PRODUCTION-GRADE GRAPHRAG VS FLAT RAG

**Thời lượng:** 120 phút  
**Môi trường:** Google Colab (T4 GPU khuyến nghị) + Neo4j AuraDB  
**Dữ liệu:** HackerNoon Tech Company News Data Dump (bản thu gọn do giảng viên cung cấp)  
**Công cụ:** Học viên được dùng AI Coding Agent, nhưng phải tự thiết kế, kiểm thử và giải thích logic.

## 🎯 Mục tiêu
1. Xây dựng Hybrid GraphRAG end-to-end.
2. Xử lý Coreference Resolution, Entity Resolution và Super-node Mitigation.
3. Bulk insert bằng `UNWIND`, không insert từng row.
4. So sánh Flat RAG và GraphRAG bằng Golden Dataset + LLM-as-a-Judge.
5. Đo quality, latency và token usage.
6. Giải thích kiến trúc và failure modes.

> Notebook là **reference lab guide**: có code khung chạy được nhưng vẫn yêu cầu học viên thay prompt/threshold/retrieval policy và thuyết minh lựa chọn.

## ⏳ Timeline

| Phút | Nội dung |
|---|---|
| 00–15 | Setup, load, dedup, chunk, coreference |
| 15–45 | NER/RE, entity resolution, Neo4j bulk insert |
| 45–75 | Flat RAG, graph traversal, hybrid retrieval |
| 75–105 | Golden Dataset, LLM-as-a-Judge, comparison |
| 105–120 | Failure-mode tests, bonus, export, thuyết minh |

### Scale guard
Trong lab 2 giờ, không nên gửi toàn bộ 350MB qua LLM. Mặc định dùng subset:
- `LAB_MAX_ARTICLES = 1500`
- `LAB_MAX_CHUNKS = 3000`
- `EXTRACTION_MAX_CHUNKS = 400`

Kiến trúc phải scale được; volume trong giờ lab chỉ dùng để chứng minh pipeline.

# PHẦN 1 — SETUP & PREPROCESSING

### Secrets trên Colab
Tạo:
- `NEO4J_URI`, `NEO4J_USER`, `NEO4J_PASSWORD`
- `GROQ_API_KEY`, `GROQ_MODEL`
- `HF_TOKEN` để stream dataset từ Hugging Face
- cho judge: `JUDGE_PROVIDER`, `JUDGE_MODEL`, và `OPENAI_API_KEY` nếu dùng OpenAI

Không hard-code API key vào notebook nộp bài.

In [1]:
#@title 1.1 — Install
# CHAY LOCAL: cac package da duoc cai san vao .venv cua repo (xem requirements.txt).
# KHONG chay lai %pip trong notebook -> cham va co the pha version dang hoat dong.
# Neu chay tren Colab, bo comment dong duoi:
# %pip -q install neo4j pandas numpy pyarrow sentence-transformers faiss-cpu groq openai tqdm networkx datasets python-dotenv
print("Bo qua cell install — dung .venv cua repo")

Bo qua cell install — dung .venv cua repo

In [2]:
#@title 1.2 — Imports & config
import os, re, json, time, random, hashlib, unicodedata
from pathlib import Path
from collections import defaultdict, Counter, deque
from difflib import SequenceMatcher

import numpy as np
import pandas as pd
from tqdm.auto import tqdm
from neo4j import GraphDatabase
from sentence_transformers import SentenceTransformer
import faiss

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
pd.set_option("display.max_colwidth", 120)

def get_secret(name, default=None):
    try:
        from google.colab import userdata
        value = userdata.get(name)
        if value is not None:
            return value
    except Exception:
        pass
    return os.environ.get(name, default)

# ============ LOCAL PATCH A — chay local thay vi Colab ============
from dotenv import load_dotenv, find_dotenv
load_dotenv(find_dotenv(usecwd=True))   # nap .env TRUOC khi doc secret

BASE_DIR  = Path.cwd()
DATA_DIR  = BASE_DIR / "data";           DATA_DIR.mkdir(exist_ok=True)
OUT_DIR   = BASE_DIR / "outputs";        OUT_DIR.mkdir(exist_ok=True)
REP_DIR   = BASE_DIR / "reports";        REP_DIR.mkdir(exist_ok=True)
CACHE_DIR = DATA_DIR / "cache";          CACHE_DIR.mkdir(exist_ok=True)

RAW_PATH    = str(DATA_DIR / "hackernoon_first5000_raw.csv")   # 5.000 dong dau (scope cua Golden set)
DATA_PATH   = str(DATA_DIR / "hackernoon_subset.csv")          # corpus da lam sach
GOLDEN_SRC  = str(DATA_DIR / "graphrag_golden_50_first5000_detailed.csv")
GOLDEN_PATH = str(DATA_DIR / "golden_dataset.csv")
CHECKPOINT  = str(OUT_DIR  / "graphrag_eval_checkpoint.csv")
COREF_CACHE = str(CACHE_DIR / "coref_cache.csv")
TRIPLE_CACHE= str(CACHE_DIR / "triples_cache.csv")

NEO4J_URI      = get_secret("NEO4J_URI", "")
NEO4J_USER     = get_secret("NEO4J_USER", "neo4j")
NEO4J_PASSWORD = get_secret("NEO4J_PASSWORD", "")
NEO4J_DATABASE = get_secret("NEO4J_DATABASE", "neo4j")
GROQ_API_KEY   = get_secret("GROQ_API_KEY", "")
GROQ_MODEL     = get_secret("GROQ_MODEL", "")
JUDGE_PROVIDER = get_secret("JUDGE_PROVIDER", "openai").lower()
JUDGE_MODEL    = get_secret("JUDGE_MODEL", "")
OPENAI_API_KEY = get_secret("OPENAI_API_KEY", "")
HF_TOKEN       = get_secret("HF_TOKEN", "")

# ---- Scale guard ----
# Guard goc (README): 1500 articles / 3000 chunks / 400 extraction chunks / chunk 220 tu.
# Dataset that la SNIPPET (median 42 tu/bai) -> 1 bai = 1 chunk, khoi luong token thap hon
# nhieu so voi gia dinh "full article". Giu nguyen tran chunk & extraction, chi noi tran
# article len 3000 de phu het 5.000 dong dau (scope cua Golden Dataset).
N_RAW_ROWS            = 5000
LAB_MAX_ARTICLES      = 3000
LAB_MAX_CHUNKS        = 3000
EXTRACTION_MAX_CHUNKS = 400
CHUNK_WORDS           = 220
CHUNK_OVERLAP_WORDS   = 40

# ---- Dinh tuyen LLM theo vai tro (quyet dinh do RATE LIMIT thuc te, xem bao cao muc 5) ----
# Groq free tier: 200.000 token/NGAY cho MOI model. Do pipeline can ~400k token,
# ta chia tai theo vai tro thay vi dung 1 model cho tat ca:
#   * NER + RE  -> Groq openai/gpt-oss-20b : buoc dung graph, giu tren Groq nhu de bai
#   * coref / seed / sinh cau tra loi -> OpenAI gpt-4o-mini : nhanh, khong dung tran Groq
#   * LLM-as-a-Judge -> OpenAI gpt-4o-mini (theo .env)
# Ca Flat RAG lan GraphRAG dung CHUNG mot generator -> so sanh van cong bang.
EXTRACT_PROVIDER = "groq"
EXTRACT_MODEL    = get_secret("EXTRACT_MODEL", "openai/gpt-oss-20b")
GEN_PROVIDER     = "openai" if OPENAI_API_KEY else "groq"
GEN_MODEL        = get_secret("GEN_MODEL", "gpt-4o-mini" if OPENAI_API_KEY else GROQ_MODEL)

RESET_GRAPH = True   # xoa graph truoc khi ingest -> notebook idempotent khi Run All

assert all([NEO4J_URI, NEO4J_PASSWORD, GROQ_API_KEY, GROQ_MODEL, HF_TOKEN]), "Thieu secret trong .env"
print("Config OK | extract:", EXTRACT_PROVIDER, EXTRACT_MODEL,
      "| generate:", GEN_PROVIDER, GEN_MODEL, "| judge:", JUDGE_PROVIDER, JUDGE_MODEL)
# KHONG print gia tri API key ra output cell (rubric tru -10 diem neu lo key).

D:\VINUNI\d19\K4-Track3-Lab19-GraphRAG-2A202601748-DuongNgocHai\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Config OK | extract: groq openai/gpt-oss-20b | generate: openai gpt-4o-mini | judge: openai gpt-4o-mini

## 1.3 — Nap dataset: vi sao lay dung 5.000 dong dau

Dataset that (`HackerNoon/tech-company-news-data-dump`, 8.079.363 dong) **khong co cot `text`**:
noi dung nam o `title` + `description` (snippet ~40 tu), va cac dong duoc **sap xep theo `companyName`**.

Bo **Golden Dataset 25 cau** trong `data/graphrag_golden_50_first5000_detailed.csv` duoc xay tren
**5.000 dong dau**: cot `evidence_row_ids_0based` tro thang vao chi so dong goc.

> **Quyet dinh thiet ke:** lay dung 5.000 dong dau lam corpus. Doi lai tinh dai dien thong ke, ta duoc:
> 1. moi cau hoi vang deu co bang chung nam trong corpus -> benchmark do **nang luc kien truc**,
>    thay vi do "may man co du lieu hay khong";
> 2. `article_id = row<row_id>` -> **provenance kiem chung duoc den tung dong du lieu goc**;
> 3. tinh duoc **Evidence Recall** khach quan (retrieval co lay dung chunk vang khong) — tach bach
>    loi *retrieval* voi loi *generation* khi phan tich ca hong.

In [3]:
#@title 1.3 — Stream HackerNoon -> CSV (scope = 5.000 dong dau, khop Golden Dataset)
# QUYET DINH THIET KE (xem markdown phia tren):
#   Golden Dataset trong data/graphrag_golden_50_first5000_detailed.csv duoc xay tren
#   5.000 DONG DAU cua dataset (cot evidence_row_ids_0based tro thang vao chi so dong).
#   => Lay dung 5.000 dong dau lam corpus thi moi cau hoi vang deu co bang chung trong corpus,
#      va moi chunk_id map 1-1 voi row_id -> kiem chung provenance den tung dong du lieu goc.
import os, itertools
from datasets import load_dataset

DATASET_NAME = "HackerNoon/tech-company-news-data-dump"

if not HF_TOKEN:
    raise ValueError("Thieu HF_TOKEN trong .env")

if Path(RAW_PATH).exists():
    raw_first5000 = pd.read_csv(RAW_PATH)
    print(f"[cache] da co {RAW_PATH} -> bo qua streaming")
else:
    ds = load_dataset(DATASET_NAME, split="train", streaming=True, token=HF_TOKEN)
    rows = list(tqdm(itertools.islice(ds, 0, N_RAW_ROWS), total=N_RAW_ROWS, desc="Streaming"))
    raw_first5000 = pd.DataFrame(rows)
    raw_first5000["row_id"] = range(len(raw_first5000))
    raw_first5000.to_csv(RAW_PATH, index=False)

if "row_id" not in raw_first5000.columns:
    raw_first5000["row_id"] = range(len(raw_first5000))

print("Cot that cua dataset:", raw_first5000.columns.tolist())
print(f"rows={len(raw_first5000):,} | size={os.path.getsize(RAW_PATH)/1e6:.1f} MB -> {RAW_PATH}")

# Audit du lieu tho: description rong / thieu ngay -> giai thich vi sao phai loc o cell 1.5
_d = raw_first5000.description.fillna("").astype(str)
print("description rong          :", int((_d.str.len() == 0).sum()))
print("description >= 120 ky tu  :", int((_d.str.len() >= 120).sum()))
print("published_at bi thieu     :", int(raw_first5000.published_at.isna().sum()))
display(raw_first5000.head(3)[["row_id", "companyName", "published_at", "title"]])

[cache] da co d:\VINUNI\d19\K4-Track3-Lab19-GraphRAG-2A202601748-DuongNgocHai\data\hackernoon_first5000_raw.csv -> bo qua streaming
Cot that cua dataset: ['companyName', 'companyUrl', 'published_at', 'url', 'title', 'main_image', 'description', 'row_id']
rows=5,000 | size=3.1 MB -> d:\VINUNI\d19\K4-Track3-Lab19-GraphRAG-2A202601748-DuongNgocHai\data\hackernoon_first5000_raw.csv
description rong          : 2306
description >= 120 ky tu  : 2584
published_at bi thieu     : 2297

,row_id,companyName,published_at,title
0,0,01Synergy,2023-05-16 02:09:00,onsemi and Sineng Electric Spearhead the Development of Sustainable Energy Applications
1,1,01Synergy,2023-05-02 00:07:00,Adobe student receives national Information and Technology award
2,2,01Synergy,2023-05-01 22:22:00,Modernizing State Services: Harnessing Technology for Enhanced Public Service Delivery

In [4]:
#@title 1.4 — Neo4j connection + schema
driver = None

def connect_neo4j():
    global driver
    if not NEO4J_URI or not NEO4J_PASSWORD:
        raise ValueError("Thiếu Neo4j secrets.")
    driver = GraphDatabase.driver(
        NEO4J_URI,
        auth=(NEO4J_USER, NEO4J_PASSWORD),
    )
    driver.verify_connectivity()
    print("✅ Neo4j connected.")

def run_cypher(query, **params):
    if driver is None:
        raise RuntimeError("Hãy chạy connect_neo4j() trước.")
    with driver.session(database=NEO4J_DATABASE) as session:
        result = session.run(query, **params)
        rows = [r.data() for r in result]
        result.consume()
    return rows

def setup_graph_schema():
    for stmt in [
        """
        CREATE CONSTRAINT entity_id IF NOT EXISTS
        FOR (n:Entity) REQUIRE n.id IS UNIQUE
        """,
        """
        CREATE INDEX entity_name_norm IF NOT EXISTS
        FOR (n:Entity) ON (n.name_norm)
        """,
        """
        CREATE INDEX company_name_norm IF NOT EXISTS
        FOR (n:Company) ON (n.name_norm)
        """,
        """
        CREATE INDEX person_name_norm IF NOT EXISTS
        FOR (n:Person) ON (n.name_norm)
        """,
        """
        CREATE INDEX technology_name_norm IF NOT EXISTS
        FOR (n:Technology) ON (n.name_norm)
        """,
    ]:
        run_cypher(stmt)
    print("✅ Schema ready.")

connect_neo4j()
setup_graph_schema()

✅ Neo4j connected.
✅ Schema ready.

In [5]:
#@title 1.5 — Loader + exact dedup + chunking
def norm_space(x):
    return re.sub(r"\s+", " ", str(x or "")).strip()

def sha1(x):
    return hashlib.sha1(str(x).encode("utf-8", errors="ignore")).hexdigest()

def pick_col(df, candidates, required=True):
    lookup = {str(c).lower(): c for c in df.columns}
    for c in candidates:
        if c.lower() in lookup:
            return lookup[c.lower()]
    if required:
        raise KeyError(f"Missing one of columns: {candidates}")
    return None

def load_news(path):
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(path)
    if path.suffix.lower() == ".csv":
        return pd.read_csv(path)
    if path.suffix.lower() in {".jsonl", ".ndjson"}:
        return pd.read_json(path, lines=True)
    if path.suffix.lower() == ".json":
        return pd.read_json(path)
    if path.suffix.lower() in {".parquet", ".pq"}:
        return pd.read_parquet(path)
    raise ValueError(f"Unsupported: {path.suffix}")

def standardize_news(raw):
    text_col = pick_col(raw, ["text", "content", "article", "body", "story"])
    title_col = pick_col(raw, ["title", "headline"], required=False)
    date_col = pick_col(raw, ["published_date", "date", "published_at", "created_at"], required=False)
    id_col = pick_col(raw, ["id", "article_id", "story_id", "uuid"], required=False)

    df = pd.DataFrame()
    df["text"] = raw[text_col].fillna("").map(norm_space)
    df["title"] = raw[title_col].fillna("").map(norm_space) if title_col else ""

    if date_col:
        df["published_date"] = (
            pd.to_datetime(raw[date_col], errors="coerce", utc=True)
            .dt.strftime("%Y-%m-%d")
            .fillna("")
        )
    else:
        df["published_date"] = ""

    if id_col:
        df["article_id"] = raw[id_col].astype(str)
    else:
        df["article_id"] = [
            sha1(f"{t}\n{x}")[:20] for t, x in zip(df["title"], df["text"])
        ]

    df = df[df["text"].str.len() >= 80].copy()
    df["dedup_key"] = [
        sha1(norm_space(f"{t}\n{x}").lower())
        for t, x in zip(df["title"], df["text"])
    ]
    before = len(df)
    df = df.drop_duplicates("dedup_key").drop(columns="dedup_key").reset_index(drop=True)
    print(f"Exact dedup: {before:,} -> {len(df):,}")

    if LAB_MAX_ARTICLES and len(df) > LAB_MAX_ARTICLES:
        df = df.sample(LAB_MAX_ARTICLES, random_state=SEED).sort_index().reset_index(drop=True)
    return df

def chunk_text(text, size=220, overlap=40):
    words = norm_space(text).split()
    step = max(1, size - overlap)
    out = []
    for start in range(0, len(words), step):
        part = words[start:start+size]
        if not part:
            break
        out.append(" ".join(part))
        if start + size >= len(words):
            break
    return out

def build_chunks(news_df):
    rows = []
    for r in tqdm(news_df.itertuples(index=False), total=len(news_df), desc="Chunking"):
        for i, text in enumerate(chunk_text(r.text, CHUNK_WORDS, CHUNK_OVERLAP_WORDS)):
            rows.append({
                "chunk_id": f"{r.article_id}::c{i:04d}",
                "article_id": r.article_id,
                "title": r.title,
                "published_date": r.published_date,
                "text": text,
            })
            if LAB_MAX_CHUNKS and len(rows) >= LAB_MAX_CHUNKS:
                return pd.DataFrame(rows)
    return pd.DataFrame(rows)

# ======== Patch C — dataset KHONG co cot 'text' -> ghep title + description ========
raw_df = raw_first5000.copy()
raw_df["text"] = (
    raw_df["title"].fillna("").astype(str).str.strip() + ". " +
    raw_df["description"].fillna("").astype(str).str.strip()
).str.strip()

# article_id = so dong goc -> provenance truy nguoc thang ve evidence_row_ids cua Golden set
raw_df["article_id"] = ["row%05d" % int(i) for i in raw_df["row_id"]]

before_filter = len(raw_df)
raw_df = raw_df[raw_df["text"].str.len() >= 120].reset_index(drop=True)
print(f"Loc snippet qua ngan (<120 ky tu): {before_filter:,} -> {len(raw_df):,}")

news_df   = standardize_news(raw_df)     # pick_col gio tim thay 'text', 'title', 'published_at', 'article_id'
chunks_df = build_chunks(news_df)
print("articles:", len(news_df), "| chunks:", len(chunks_df))
print("Chunk/article ratio:", round(len(chunks_df)/max(len(news_df),1), 2))
print("Ty le chunk thieu published_date:", float((chunks_df.published_date.fillna("") == "").mean()))
print("So tu trung binh moi chunk:", int(chunks_df.text.str.split().str.len().median()))
chunks_df.to_csv(DATA_PATH, index=False)
display(chunks_df.head(3))

Loc snippet qua ngan (<120 ky tu): 5,000 -> 2,687

Exact dedup: 2,687 -> 2,114

Chunking:   0%|          | 0/2114 [00:00<?, ?it/s]

Chunking:  79%|███████▉  | 1665/2114 [00:00<00:00, 16513.40it/s]

Chunking: 100%|██████████| 2114/2114 [00:00<00:00, 15787.18it/s]

articles: 2114 | chunks: 2114
Chunk/article ratio: 1.0
Ty le chunk thieu published_date: 0.0
So tu trung binh moi chunk: 42

,chunk_id,article_id,title,published_date,text
0,row00000::c0000,row00000,onsemi and Sineng Electric Spearhead the Development of Sustainable Energy Applications,2023-05-16,onsemi and Sineng Electric Spearhead the Development of Sustainable Energy Applications. (Nasdaq: ON) a leader in in...
1,row00001::c0000,row00001,Adobe student receives national Information and Technology award,2023-05-02,Adobe student receives national Information and Technology award. ELKO — An eighth grader at Adobe Middle School is ...
2,row00002::c0000,row00002,Modernizing State Services: Harnessing Technology for Enhanced Public Service Delivery,2023-05-01,Modernizing State Services: Harnessing Technology for Enhanced Public Service Delivery. To deliver 21st-century gove...

### 🎯 AI Coding Agent Challenge A — Near Dedup
Exact hash không bắt được bài repost/near-duplicate.

Hãy dùng AI Agent thiết kế thêm **MinHash/LSH, SimHash hoặc embedding+ANN**.  
**Không chấp nhận** pairwise cosine `O(N²)` trên toàn dataset.

Trong báo cáo nêu:
1. threshold,
2. false positive,
3. cách audit cặp bị merge.

In [6]:
#@title 1.6 — LLM wrapper (multi-provider) + retry + JSON parsing
from groq import Groq
from openai import OpenAI

groq_client = Groq(api_key=GROQ_API_KEY) if GROQ_API_KEY else None
openai_client = OpenAI(api_key=OPENAI_API_KEY) if OPENAI_API_KEY else None

LLM_CALL_LOG = []   # log token/latency tung call -> vat lieu cho phan tich chi phi

def parse_json_object(text):
    text = str(text).strip()
    text = re.sub(r"^```(?:json)?\s*", "", text, flags=re.I)
    text = re.sub(r"\s*```$", "", text)
    a, b = text.find("{"), text.rfind("}")
    if a < 0 or b <= a:
        raise ValueError("No JSON object found.")
    return json.loads(text[a:b+1])

def llm_chat(messages, provider, model, json_mode=False, max_retries=5,
             reasoning_effort=None, tag=""):
    """Goi 1 LLM (groq hoac openai) voi retry + exponential backoff.
    Ton trong goi y 'try again in Xs' cua Groq 429 thay vi doan mu."""
    last = None
    for attempt in range(max_retries):
        try:
            t0 = time.perf_counter()
            if provider == "groq":
                if groq_client is None:
                    raise RuntimeError("Thieu GROQ_API_KEY.")
                kwargs = {"model": model, "messages": messages, "temperature": 0.0}
                if json_mode:
                    kwargs["response_format"] = {"type": "json_object"}
                if reasoning_effort:
                    kwargs["reasoning_effort"] = reasoning_effort
                resp = groq_client.chat.completions.create(**kwargs)
            elif provider == "openai":
                if openai_client is None:
                    raise RuntimeError("Thieu OPENAI_API_KEY.")
                kwargs = {"model": model, "messages": messages, "temperature": 0.0}
                if json_mode:
                    kwargs["response_format"] = {"type": "json_object"}
                resp = openai_client.chat.completions.create(**kwargs)
            else:
                raise ValueError("provider phai la 'groq' hoac 'openai'")

            usage = {}
            if getattr(resp, "usage", None):
                usage = {"prompt_tokens": getattr(resp.usage, "prompt_tokens", None),
                         "completion_tokens": getattr(resp.usage, "completion_tokens", None),
                         "total_tokens": getattr(resp.usage, "total_tokens", None)}
            LLM_CALL_LOG.append({"tag": tag, "provider": provider, "model": model,
                                 "latency_s": round(time.perf_counter()-t0, 2),
                                 "total_tokens": usage.get("total_tokens"),
                                 "retries": attempt})
            return resp.choices[0].message.content, usage
        except Exception as e:
            last = e
            if attempt == max_retries - 1:
                break
            wait = min(30, 2 ** attempt + random.random())
            m = re.search(r"try again in ([0-9.]+)s", str(e))
            if m:
                wait = min(60, float(m.group(1)) + 1.0)
            time.sleep(wait)
    raise RuntimeError(last)

def llm_json(system, user, provider, model, reasoning_effort=None, tag=""):
    text, usage = llm_chat([{"role": "system", "content": system},
                            {"role": "user", "content": user}],
                           provider=provider, model=model, json_mode=True,
                           reasoning_effort=reasoning_effort, tag=tag)
    return parse_json_object(text), usage

# Cac shortcut theo vai tro (xem bang dinh tuyen o cell 1.2)
def extract_json(system, user, tag="extract"):
    return llm_json(system, user, EXTRACT_PROVIDER, EXTRACT_MODEL,
                    reasoning_effort="low", tag=tag)

def gen_json(system, user, tag="gen"):
    return llm_json(system, user, GEN_PROVIDER, GEN_MODEL, tag=tag)

def gen_chat(messages, tag="gen"):
    return llm_chat(messages, GEN_PROVIDER, GEN_MODEL, tag=tag)

# Tuong thich nguoc voi code khung (cac cell sau van goi groq_chat/groq_json)
def groq_chat(messages, model=None, json_mode=False, max_retries=5, reasoning_effort=None, tag=""):
    return llm_chat(messages, "groq", model or GROQ_MODEL, json_mode=json_mode,
                    max_retries=max_retries, reasoning_effort=reasoning_effort, tag=tag)

def groq_json(system, user, model=None, reasoning_effort=None, tag=""):
    return llm_json(system, user, "groq", model or GROQ_MODEL,
                    reasoning_effort=reasoning_effort, tag=tag)

def llm_cost_summary():
    if not LLM_CALL_LOG:
        return pd.DataFrame()
    df = pd.DataFrame(LLM_CALL_LOG)
    return (df.groupby(["tag", "provider", "model"])
              .agg(calls=("total_tokens", "size"),
                   tokens=("total_tokens", "sum"),
                   latency_s=("latency_s", "sum"),
                   retries=("retries", "sum"))
              .reset_index().sort_values("tokens", ascending=False))

print("LLM routing | extract:", EXTRACT_PROVIDER, EXTRACT_MODEL,
      "| generate/coref/seed:", GEN_PROVIDER, GEN_MODEL,
      "| judge:", JUDGE_PROVIDER, JUDGE_MODEL)

LLM routing | extract: groq openai/gpt-oss-20b | generate/coref/seed: openai gpt-4o-mini | judge: openai gpt-4o-mini

## 1.7 — Coreference Resolution

Yêu cầu:
- chỉ resolve đại từ khi antecedent rõ trong cùng chunk,
- không invent fact,
- giữ nguyên số/ngày/ticker/product,
- ambiguity → giữ nguyên và log `unresolved_mentions`.

**Failure mode quan trọng:** false coreference → false edge.

In [7]:
#@title 1.7 — Coreference resolution theo batch (co rule-gate truoc LLM)
COREF_SYSTEM = """
You are a conservative coreference-resolution component for a knowledge-graph pipeline.
Resolve pronouns and generic references only when the antecedent is clearly supported in the same chunk.
Never invent facts. Preserve dates, numbers, tickers and product names.
If a mention is ambiguous, leave the text unchanged and list it in unresolved_mentions.
Return strict JSON only.
""".strip()

# Rule-gate: chi chunk co dai tu / tham chieu chung moi can goi LLM.
# Snippet tin tuc thuong tu chua ten day du -> gate nay cat ~40-60% so call,
# la toi uu quan trong nhat khi rate limit tinh theo TOKEN/PHUT (Groq free: 8k TPM).
PRONOUN_RE = re.compile(
    r"\b(it|its|it's|they|them|their|theirs|he|him|his|she|her|hers|"
    r"the company|the companies|the startup|the firm|the group|the maker|the vendor|"
    r"the platform|the deal|the acquisition|the partnership|this deal|these solutions|"
    r"the technology|the product|the service)\b", re.I)

def needs_coref(text):
    return bool(PRONOUN_RE.search(str(text)))

def resolve_coref_batch(batch_df):
    payload = [{"chunk_id": r.chunk_id, "text": r.text}
               for r in batch_df.itertuples(index=False)]

    prompt = f"""
Resolve coreferences. Return a json object shaped exactly like:
{{
  "items": [
    {{
      "chunk_id": "...",
      "resolved_text": "...",
      "unresolved_mentions": ["..."]
    }}
  ]
}}

INPUT:
{json.dumps(payload, ensure_ascii=False)}
""".strip()

    obj, usage = gen_json(COREF_SYSTEM, prompt, tag="coref")
    by_id = {x.get("chunk_id"): x for x in obj.get("items", [])}

    rows = []
    for r in batch_df.itertuples(index=False):
        item = by_id.get(r.chunk_id, {})
        rows.append({
            "chunk_id": r.chunk_id,
            "resolved_text": norm_space(item.get("resolved_text") or r.text),
            "unresolved_mentions": item.get("unresolved_mentions", []),
            "coref_route": "LLM",
        })
    return pd.DataFrame(rows), usage

def run_coref(chunks_subset, batch_size=6):
    """Chi goi LLM cho chunk co dai tu; phan con lai giu nguyen van (route=RULE_SKIP)."""
    gated = chunks_subset[chunks_subset.text.map(needs_coref)]
    skipped = chunks_subset[~chunks_subset.chunk_id.isin(set(gated.chunk_id))]
    print(f"Coref rule-gate: {len(gated)} chunk can LLM | {len(skipped)} chunk bo qua (khong co dai tu)")

    out = []
    if len(skipped):
        out.append(pd.DataFrame({
            "chunk_id": skipped.chunk_id.tolist(),
            "resolved_text": skipped.text.map(norm_space).tolist(),
            "unresolved_mentions": [[] for _ in range(len(skipped))],
            "coref_route": ["RULE_SKIP"] * len(skipped),
        }))

    for start in tqdm(range(0, len(gated), batch_size), desc="Coref"):
        batch = gated.iloc[start:start+batch_size]
        try:
            df, _ = resolve_coref_batch(batch)
        except Exception as e:
            print("Coref batch loi:", str(e)[:120])
            df = pd.DataFrame({
                "chunk_id": batch["chunk_id"].tolist(),
                "resolved_text": batch["text"].tolist(),
                "unresolved_mentions": [["COREF_BATCH_FAILED"] for _ in range(len(batch))],
                "coref_route": ["FAILED"] * len(batch),
            })
        out.append(df)
    return pd.concat(out, ignore_index=True)

# ================= CHON SUBSET TRICH XUAT (entity-anchored stratified sampling) =================
# Ngan sach trich xuat co dinh (EXTRACTION_MAX_CHUNKS=400 / 2.1k chunk). Lay ngau nhien 400 chunk
# tren mot corpus tin tuc rai rac -> do thi thua, gan nhu khong co canh noi 2 bai bao => multi-hop
# khong ton tai. Chinh sach chon:
#   Tier 1: chunk chua bang chung cua Golden Dataset (bat buoc phu, de benchmark co nghia)
#   Tier 2: chunk giau thuc the (nhieu anchor big-tech) -> tao mat do canh & super-node
#   Tier 3: ngau nhien co seed -> giu tinh da dang, tranh do thi chi xoay quanh 1 cum
golden_src_df = pd.read_csv(GOLDEN_SRC)
evidence_rows = sorted({int(i) for s in golden_src_df.evidence_row_ids_0based for i in json.loads(s)})
evidence_article_ids = {"row%05d" % i for i in evidence_rows}

ANCHORS = sorted({
    "microsoft","google","alphabet","openai","chatgpt","meta","facebook","apple","nvidia","amazon",
    "aws","anthropic","claude","tesla","ibm","oracle","samsung","intel","amd","qualcomm","salesforce",
    "adobe","dell","hpe","hewlett packard","snowflake","cohere","h2o.ai","keysight","synopsys",
    "palo alto networks","thales","l&t technology","white house","azure","gemini","copilot","llm",
    "artificial intelligence","generative ai","machine learning","acquisition","acquired","acquires",
    "invests","investment","funding","partnership","partners with","launches","ceo","founder",
})
anchor_re = re.compile("|".join(re.escape(a) for a in ANCHORS), re.I)

scored = chunks_df.copy()
scored["anchor_hits"] = scored.text.map(lambda t: len(set(m.group(0).lower() for m in anchor_re.finditer(t))))
scored["is_golden_evidence"] = scored.article_id.isin(evidence_article_ids)

tier1 = scored[scored.is_golden_evidence]
tier2 = (scored[~scored.is_golden_evidence & (scored.anchor_hits >= 2)]
         .sort_values("anchor_hits", ascending=False))
tier3 = (scored[~scored.is_golden_evidence & (scored.anchor_hits == 1)]
         .sample(frac=1.0, random_state=SEED))

extraction_source = (pd.concat([tier1, tier2, tier3])
                     .head(EXTRACTION_MAX_CHUNKS)
                     .reset_index(drop=True).copy())

print(f"Extraction subset: {len(extraction_source)} chunk "
      f"| tier1 golden-evidence={int(extraction_source.is_golden_evidence.sum())}/{len(evidence_article_ids)}"
      f" | anchor_hits trung binh={extraction_source.anchor_hits.mean():.2f}")
assert extraction_source.is_golden_evidence.sum() == len(evidence_article_ids & set(chunks_df.article_id)), \
    "Thieu chunk bang chung cua Golden Dataset trong subset trich xuat"

# ================= COREFERENCE (co cache tren dia, chi goi LLM cho chunk moi) =================
def run_coref_cached(chunks_subset, batch_size=6):
    done = pd.DataFrame(columns=["chunk_id", "resolved_text", "unresolved_mentions", "coref_route"])
    if Path(COREF_CACHE).exists():
        done = pd.read_csv(COREF_CACHE)
        done["unresolved_mentions"] = done.unresolved_mentions.fillna("[]").map(json.loads)
    todo = chunks_subset[~chunks_subset.chunk_id.isin(set(done.chunk_id))]
    print(f"Coref: {len(done)} chunk lay tu cache | {len(todo)} chunk goi LLM")
    if len(todo):
        fresh = run_coref(todo, batch_size=batch_size)
        done = pd.concat([done, fresh], ignore_index=True)
        out = done.copy()
        out["unresolved_mentions"] = out.unresolved_mentions.map(json.dumps)
        out.to_csv(COREF_CACHE, index=False)
    return done[done.chunk_id.isin(set(chunks_subset.chunk_id))].reset_index(drop=True)

coref_df = run_coref_cached(extraction_source, batch_size=6)
extraction_source = extraction_source.merge(coref_df, on="chunk_id", how="left")
extraction_source["resolved_text"] = extraction_source.resolved_text.fillna(extraction_source.text)
print("Phan bo route coref:", extraction_source.coref_route.value_counts().to_dict())

# Spot-check bat buoc (vat lieu cho cau thuyet minh #1)
mask = extraction_source.unresolved_mentions.map(lambda x: bool(x) and len(x) > 0)
print("Chunk co unresolved_mentions:", int(mask.sum()), "/", len(extraction_source))
display(extraction_source.loc[mask, ["chunk_id", "unresolved_mentions"]].head(10))

changed = extraction_source[extraction_source.text.map(norm_space) != extraction_source.resolved_text.map(norm_space)]
print("Chunk bi coref sua:", len(changed), f"({len(changed)/max(len(extraction_source),1):.1%})")
for _, r in changed.head(3).iterrows():
    print("-" * 70)
    print("chunk_id:", r.chunk_id)
    print("BEFORE:", r.text[:260])
    print("AFTER :", r.resolved_text[:260])

Extraction subset: 400 chunk | tier1 golden-evidence=28/28 | anchor_hits trung binh=1.67
Coref: 400 chunk lay tu cache | 0 chunk goi LLM
Phan bo route coref: {'LLM': 216, 'RULE_SKIP': 184}
Chunk co unresolved_mentions: 0 / 400

Empty DataFrame
Columns: [chunk_id, unresolved_mentions]
Index: []

Chunk bi coref sua: 114 (28.5%)
----------------------------------------------------------------------
chunk_id: row00472::c0000
BEFORE: Samsung unveils OLED display with embedded heart rate sensor. It is a separate module attached under the display panel. These solutions can only detect fingerprints within a designated area which is typically directly above them. Samsung’s Sensor OLED Display
AFTER : Samsung unveils OLED display with embedded heart rate sensor. The OLED display is a separate module attached under the display panel. These solutions can only detect fingerprints within a designated area which is typically directly above them. Samsung’s Sensor
----------------------------------------------------------------------
chunk_id: row02449::c0000
BEFORE: OpenAI plans app store for AI software The Information reports. plans to launch a marketplace that will allow developers to sell their AI models built on top of its own AI technology news site the Information reported on Tuesday citing people with knowledge ..
AFTER : OpenAI plans app store for AI software The Information reports. OpenAI plans to launch a marketplace that will allow developers to sell their AI models built on top of its own AI technology news site the Information reported on Tuesday citing people with knowl
----------------------------------------------------------------------
chunk_id: row02537::c0000
BEFORE: Amazon has drawn thousands to try its AI service competing with Microsoft Google. The company also announced new AI tools on Wednesday including a program for building more conversational customer-service agents technology access from the startup Cohere and a
AFTER : Amazon has drawn thousands to try its AI service competing with Microsoft and Google. The company also announced new AI tools on Wednesday including a program for building more conversational customer-service agents, technology access from the startup Cohere,

# PHẦN 2 — TRIPLE EXTRACTION & NEO4J BULK INSERT (15–45')

## Graph schema
**Nodes:** `Company`, `Person`, `Technology` + base label `Entity`.

**Relations:** `ACQUIRED`, `DEVELOPED`, `INVESTED_IN`, `FOUNDED`, `WORKED_AT`, `PARTNERED_WITH`, `USES`, `LEADS`.

**Mỗi edge bắt buộc:** `source_chunk_id`, `published_date`; khuyến nghị thêm `evidence`, `confidence`.

> Relation type phải qua allowlist trước khi ghép vào Cypher.

In [8]:
#@title 2.1 — NER + RE extraction
ALLOWED_NODE_TYPES = {"Company", "Person", "Technology"}
ALLOWED_RELATIONS = {
    "ACQUIRED", "DEVELOPED", "INVESTED_IN", "FOUNDED",
    "WORKED_AT", "PARTNERED_WITH", "USES", "LEADS"
}

EXTRACT_SYSTEM = f"""
Extract a high-precision knowledge graph from tech-news text.
Allowed node types: {sorted(ALLOWED_NODE_TYPES)}
Allowed relations: {sorted(ALLOWED_RELATIONS)}
Use only explicitly supported facts. Prefer precision over recall.
Every relation needs short evidence. Return strict JSON only.
""".strip()

def extract_batch(batch_df):
    payload = [{
        "chunk_id": r.chunk_id,
        "published_date": r.published_date,
        "text": getattr(r, "resolved_text", None) or r.text,
    } for r in batch_df.itertuples(index=False)]

    prompt = f"""
Return:
{{
  "items": [
    {{
      "chunk_id": "...",
      "relations": [
        {{
          "source": "...",
          "source_type": "Company|Person|Technology",
          "relation": "ALLOWED_RELATION",
          "target": "...",
          "target_type": "Company|Person|Technology",
          "evidence": "...",
          "confidence": 0.0
        }}
      ]
    }}
  ]
}}

INPUT:
{json.dumps(payload, ensure_ascii=False)}
""".strip()
    return extract_json(EXTRACT_SYSTEM, prompt)

def parse_extraction_items(obj, meta):
    """Doc ket qua LLM mot cach PHONG THU.

    Model nho (gpt-oss-20b) thinh thoang tra ve 'items' la list string hoac thieu key.
    Neu tin tuong schema mu quang thi ca batch chet -> mat du lieu. O day moi phan tu
    sai schema chi bi bo qua va dem vao thong ke schema_violations."""
    triples, violations = [], 0
    for item in obj.get("items", []):
        if not isinstance(item, dict):
            violations += 1
            continue
        cid = item.get("chunk_id")
        if cid not in meta:
            violations += 1
            continue
        for x in item.get("relations", []) or []:
            if not isinstance(x, dict):
                violations += 1
                continue
            s, t_ = norm_space(x.get("source")), norm_space(x.get("target"))
            st, tt, rel = x.get("source_type"), x.get("target_type"), x.get("relation")
            if not s or not t_:
                violations += 1
                continue
            if st not in ALLOWED_NODE_TYPES or tt not in ALLOWED_NODE_TYPES:
                violations += 1          # schema allowlist chan node type la
                continue
            if rel not in ALLOWED_RELATIONS:
                violations += 1          # schema allowlist chan quan he la
                continue
            try:
                conf = float(x.get("confidence") or 0.0)
            except (TypeError, ValueError):
                conf = 0.0
            triples.append({
                "source_raw": s, "source_type": st,
                "relation": rel,
                "target_raw": t_, "target_type": tt,
                "source_chunk_id": cid,
                "published_date": meta[cid] or "",
                "evidence": norm_space(x.get("evidence")),
                "confidence": max(0.0, min(1.0, conf)),
            })
    return triples, violations

def run_extraction(source_df, batch_size=4, on_batch=None):
    meta = source_df.set_index("chunk_id")["published_date"].to_dict()
    triples, errors = [], []
    total_violations = 0

    for start in tqdm(range(0, len(source_df), batch_size), desc="NER+RE"):
        batch = source_df.iloc[start:start+batch_size]
        try:
            obj, _ = extract_batch(batch)
            rows, v = parse_extraction_items(obj, meta)
        except Exception as e:
            # Batch hong -> ha xuong tung chunk mot de khong mat ca lo
            rows, v = [], 0
            for i in range(len(batch)):
                one = batch.iloc[i:i+1]
                try:
                    obj1, _ = extract_batch(one)
                    r1, v1 = parse_extraction_items(obj1, meta)
                    rows += r1
                    v += v1
                except Exception as e2:
                    errors.append({"chunk_id": one.chunk_id.iloc[0], "error": str(e2)[:200]})
        triples += rows
        total_violations += v
        if on_batch:                      # checkpoint tang dan -> cham tran rate limit khong mat du lieu
            on_batch(rows, batch.chunk_id.tolist())

    print("Schema violations bi loai bo:", total_violations)
    return pd.DataFrame(triples), pd.DataFrame(errors)

# ============ Chay extraction co cache tren dia (chi goi LLM cho chunk chua trich) ============
PROCESSED_CACHE = str(CACHE_DIR / "extracted_chunk_ids.csv")

def run_extraction_cached(source_df, batch_size=4):
    cached_triples = pd.read_csv(TRIPLE_CACHE) if Path(TRIPLE_CACHE).exists() else pd.DataFrame()
    processed = set(pd.read_csv(PROCESSED_CACHE).chunk_id) if Path(PROCESSED_CACHE).exists() else set()

    todo = source_df[~source_df.chunk_id.isin(processed)]
    print(f"Extraction: {len(source_df)-len(todo)} chunk tu cache | {len(todo)} chunk goi LLM")

    errors_df = pd.DataFrame()
    if len(todo):
        buffer = {"triples": cached_triples, "done": set(processed)}

        def persist(rows, chunk_ids):
            if rows:
                buffer["triples"] = pd.concat([buffer["triples"], pd.DataFrame(rows)], ignore_index=True)
            buffer["done"] |= set(chunk_ids)
            buffer["triples"].to_csv(TRIPLE_CACHE, index=False)
            pd.DataFrame({"chunk_id": sorted(buffer["done"])}).to_csv(PROCESSED_CACHE, index=False)

        try:
            _, errors_df = run_extraction(todo, batch_size=batch_size, on_batch=persist)
        finally:
            cached_triples = buffer["triples"]
            processed = buffer["done"]

    if cached_triples.empty:
        return cached_triples, errors_df
    keep = cached_triples[cached_triples.source_chunk_id.isin(set(source_df.chunk_id))]
    return keep.reset_index(drop=True), errors_df

raw_triples_df, extraction_errors_df = run_extraction_cached(extraction_source, batch_size=4)

print("triples:", len(raw_triples_df), "| batch loi:", len(extraction_errors_df))
print("Chunk co it nhat 1 triple:", raw_triples_df.source_chunk_id.nunique(), "/", len(extraction_source))
print("Phan bo relation:", raw_triples_df.relation.value_counts().to_dict())
print("confidence trung binh:", round(float(raw_triples_df.confidence.mean()), 3),
      "| ty le co evidence:", round(float((raw_triples_df.evidence.fillna("").str.len() > 0).mean()), 3))
display(raw_triples_df.head(10))
if len(extraction_errors_df):
    display(extraction_errors_df.head())

Extraction: 400 chunk tu cache | 0 chunk goi LLM
triples: 271 | batch loi: 0
Chunk co it nhat 1 triple: 205 / 400
Phan bo relation: {'PARTNERED_WITH': 68, 'DEVELOPED': 64, 'USES': 53, 'ACQUIRED': 42, 'INVESTED_IN': 14, 'WORKED_AT': 12, 'FOUNDED': 11, 'LEADS': 7}
confidence trung binh: 0.98 | ty le co evidence: 1.0

,source_raw,source_type,relation,target_raw,target_type,source_chunk_id,published_date,evidence,confidence
0,Samsung Electronics Co. Ltd.,Company,DEVELOPED,analog and logic semiconductor technologies,Technology,row00043::c0000,2023-10-05,Samsung Electronics Co. Ltd. a world leader in advanced semiconductor technology today unveiled its latest innovatio...,1.0
1,L&T Technology Services Limited,Company,PARTNERED_WITH,Thales,Company,row00261::c0000,2023-02-23,L&T Technology Services and Qualcomm Selected by Thales for Enabling 5G Private Networks in Urban Railways,1.0
2,Keysight,Company,PARTNERED_WITH,Synopsys,Company,row00272::c0000,2023-09-21,Keysight and Synopsys Partner for IoT Device Cybersecurity,1.0
3,Associated Press,Company,PARTNERED_WITH,OpenAI,Company,row00366::c0000,2023-07-13,AP Open AI agree to share select news content and technology in new collaboration,1.0
4,Samsung,Company,PARTNERED_WITH,Aqara,Company,row00395::c0000,2023-10-05,Samsung and Aqara Partners to Demonstrate Presence Sensor FP2 on SmartThings Platform,1.0
5,Aqara,Company,DEVELOPED,FP2 Presence Sensor,Technology,row00395::c0000,2023-10-05,FP2 Presence Sensor is Aqara's latest occupancy sensor,1.0
6,FP2 Presence Sensor,Technology,USES,SmartThings Platform,Technology,row00395::c0000,2023-10-05,add the SmartThings compatibility to the sensor,1.0
7,L&T Technology Services,Company,PARTNERED_WITH,Palo Alto Networks,Company,row00471::c0000,2023-06-30,L&T Technology Services Joins Forces With Palo Alto Networks as MSSP Partner,1.0
8,Samsung,Company,DEVELOPED,OLED display with embedded heart rate sensor,Technology,row00472::c0000,2023-05-23,Samsung unveils OLED display with embedded heart rate sensor,1.0
9,OLED display with embedded heart rate sensor,Technology,USES,Heart rate sensor,Technology,row00472::c0000,2023-05-23,embedded heart rate sensor,1.0

## 2.2 — Entity Resolution bằng Vector Similarity

Pipeline:
1. Manual aliases cho ticker/tên rất phổ biến.
2. Embedding ANN candidate.
3. Lexical guard để giảm false merge.
4. Xuất audit table.

### 🎯 AI Coding Agent Challenge B
Cải tiến guard cho:
- ticker,
- suffix `Inc./Corp./Ltd.`,
- product chứa company name,
- người trùng họ/tên gần giống.

In [9]:
#@title 2.2 — Entity resolution
CORP_SUFFIXES = {"inc","incorporated","corp","corporation","ltd","limited","llc","plc","co","company"}
MANUAL_ALIASES = {
    "msft": "Microsoft",
    "microsoft corp": "Microsoft",
    "microsoft corporation": "Microsoft",
    "goog": "Google",
    "googl": "Google",
    "google llc": "Google",
    "meta platforms": "Meta",
    "meta platforms inc": "Meta",
    "aapl": "Apple",
    "apple inc": "Apple",
    "hpe": "Hewlett Packard Enterprise",
    "hewlett packard": "Hewlett Packard Enterprise",
    "ltts": "L&T Technology Services",
    "l&t technology services limited": "L&T Technology Services",
    "amzn": "Amazon",
    "nvda": "NVIDIA",
    "nvidia corporation": "NVIDIA",
    "openai inc": "OpenAI",
    "alphabet inc": "Alphabet",
    "dell": "Dell Technologies",
    "dell inc": "Dell Technologies",
}

def norm_entity(name):
    s = unicodedata.normalize("NFKC", norm_space(name)).lower()
    s = re.sub(r"[^\w\s\-\.]", " ", s)
    return re.sub(r"\s+", " ", s).strip()

def strip_suffix(name):
    toks = norm_entity(name).replace(".", "").split()
    while toks and toks[-1] in CORP_SUFFIXES:
        toks.pop()
    return " ".join(toks)

def merge_guard(a, b):
    na, nb = strip_suffix(a), strip_suffix(b)
    if na == nb:
        return True
    return SequenceMatcher(None, na, nb).ratio() >= 0.72

EMBED_MODEL = "sentence-transformers/all-MiniLM-L6-v2"
embedder = None

def get_embedder():
    global embedder
    if embedder is None:
        embedder = SentenceTransformer(EMBED_MODEL)
    return embedder

class UF:
    def __init__(self, n):
        self.p = list(range(n))
    def find(self, x):
        if self.p[x] != x:
            self.p[x] = self.find(self.p[x])
        return self.p[x]
    def union(self, a, b):
        a, b = self.find(a), self.find(b)
        if a != b:
            self.p[b] = a

AUDIT_MIN_SIM = 0.75   # nguong GHI AUDIT (thap hon nguong gop) -> minh bach ca cap bi tu choi

def build_resolution_map(raw_triples_df, threshold=0.90, top_k=5):
    mentions = []
    for r in raw_triples_df.itertuples(index=False):
        mentions += [(r.source_type, r.source_raw), (r.target_type, r.target_raw)]

    counts = Counter((t, norm_entity(n)) for t, n in mentions)
    display_name = {}
    for t, n in mentions:
        display_name.setdefault((t, norm_entity(n)), n)

    mapping, audit = {}, []

    for key in counts:
        t, norm = key
        if norm in MANUAL_ALIASES:
            mapping[key] = MANUAL_ALIASES[norm]
            audit.append({
                "type": t, "left": display_name[key],
                "right": MANUAL_ALIASES[norm],
                "similarity": 1.0, "decision": "MERGE_MANUAL"
            })

    for typ in sorted(ALLOWED_NODE_TYPES):
        keys = [k for k in counts if k[0] == typ and k not in mapping]
        if not keys:
            continue
        names = [display_name[k] for k in keys]
        vecs = get_embedder().encode(
            names, batch_size=128, show_progress_bar=False,
            normalize_embeddings=True
        ).astype("float32")

        index = faiss.IndexFlatIP(vecs.shape[1])
        index.add(vecs)
        sims, nbrs = index.search(vecs, min(top_k, len(names)))
        uf = UF(len(names))

        for i in range(len(names)):
            for score, j in zip(sims[i], nbrs[i]):
                if j < 0 or i >= j or float(score) < AUDIT_MIN_SIM:
                    continue
                # Ghi audit cho MOI cap co similarity dang ke, khong chi cap duoc gop:
                # cap bi tu choi moi la bang chung cho thay guard/threshold dang lam viec.
                if float(score) < threshold:
                    decision = "REJECT_THRESHOLD"
                    ok = False
                else:
                    ok = merge_guard(names[i], names[j])
                    decision = "MERGE_VECTOR" if ok else "REJECT_GUARD"
                audit.append({
                    "type": typ, "left": names[i], "right": names[j],
                    "similarity": float(score),
                    "lexical_ratio": round(SequenceMatcher(
                        None, strip_suffix(names[i]), strip_suffix(names[j])).ratio(), 3),
                    "decision": decision
                })
                if ok:
                    uf.union(i, j)

        groups = defaultdict(list)
        for i in range(len(names)):
            groups[uf.find(i)].append(i)

        for idxs in groups.values():
            best = sorted(
                idxs,
                key=lambda i: (-counts[keys[i]], len(names[i]), names[i].lower())
            )[0]
            canonical = names[best]
            for i in idxs:
                mapping[keys[i]] = canonical

    for key in counts:
        mapping.setdefault(key, display_name[key])

    return mapping, pd.DataFrame(audit)

def canonicalize_triples(raw_df, mapping):
    df = raw_df.copy()
    def canon(name, typ):
        n = norm_entity(name)
        return mapping.get((typ, n), MANUAL_ALIASES.get(n, name))

    df["source_name"] = [canon(n,t) for n,t in zip(df.source_raw, df.source_type)]
    df["target_name"] = [canon(n,t) for n,t in zip(df.target_raw, df.target_type)]
    df["source_name_norm"] = df.source_name.map(norm_entity)
    df["target_name_norm"] = df.target_name.map(norm_entity)
    df["source_id"] = [sha1(f"{t}:{n}")[:24] for t,n in zip(df.source_type, df.source_name_norm)]
    df["target_id"] = [sha1(f"{t}:{n}")[:24] for t,n in zip(df.target_type, df.target_name_norm)]
    return df[df.source_id != df.target_id].reset_index(drop=True)

entity_map, entity_resolution_audit_df = build_resolution_map(raw_triples_df, threshold=0.90)
triples_df = canonicalize_triples(raw_triples_df, entity_map)
print("audit rows:", len(entity_resolution_audit_df), "| triples sau canonical:", len(triples_df))
if len(entity_resolution_audit_df):
    print(entity_resolution_audit_df.decision.value_counts().to_dict())
display(entity_resolution_audit_df.sort_values("similarity", ascending=False).head(20))

# ---- Thi nghiem do nhay threshold: co so de bao ve con so 0.90 (cau thuyet minh #2) ----
sweep = []
for th in [0.80, 0.85, 0.90, 0.95]:
    _m, _a = build_resolution_map(raw_triples_df, threshold=th)
    vc = _a.decision.value_counts().to_dict() if len(_a) else {}
    n_cluster = len(set(_m.values()))
    sweep.append({"threshold": th, "audit_rows": len(_a),
                  "MERGE_VECTOR": vc.get("MERGE_VECTOR", 0),
                  "REJECT_GUARD": vc.get("REJECT_GUARD", 0),
                  "MERGE_MANUAL": vc.get("MERGE_MANUAL", 0),
                  "so_entity_canonical": n_cluster})
threshold_sweep_df = pd.DataFrame(sweep)
display(threshold_sweep_df)
threshold_sweep_df.to_csv(OUT_DIR / "entity_resolution_threshold_sweep.csv", index=False)
entity_resolution_audit_df.to_csv(OUT_DIR / "entity_resolution_audit.csv", index=False)


# ---- Probe: guard co thuc su chan duoc cac cap "nguy hiem" khong? ----
# Cac cap duoi deu co similarity vector cao (cung mien ngu nghia) nhung KHONG duoc gop.
# Day la kiem chung co kiem soat cho tang Lexical Guard (cau thuyet minh #2).
GUARD_PROBE_PAIRS = [
    ("Apple", "Apple Watch"), ("Apple", "Apple Inc."),
    ("Sam Altman", "Steve Altman"), ("Google", "Google Cloud"),
    ("Meta", "Meta Platforms Inc"), ("Llama 2", "Code Llama"),
    ("Amazon", "Amazon Web Services"), ("Microsoft", "Microsoft Azure"),
    ("Dell", "Dell Technologies"), ("Synopsys", "Synopsys Inc."),
]
_probe_names = [n for pair in GUARD_PROBE_PAIRS for n in pair]
_probe_vecs = get_embedder().encode(_probe_names, normalize_embeddings=True,
                                    show_progress_bar=False).astype("float32")
guard_probe_df = pd.DataFrame([{
    "left": a, "right": b,
    "cosine": round(float(_probe_vecs[2*i] @ _probe_vecs[2*i+1]), 3),
    "lexical_ratio": round(SequenceMatcher(None, strip_suffix(a), strip_suffix(b)).ratio(), 3),
    "guard_cho_gop": merge_guard(a, b),
} for i, (a, b) in enumerate(GUARD_PROBE_PAIRS)])
guard_probe_df["ket_qua"] = np.where(
    guard_probe_df.cosine >= 0.90,
    np.where(guard_probe_df.guard_cho_gop, "MERGE_VECTOR", "REJECT_GUARD"),
    "REJECT_THRESHOLD")
display(guard_probe_df.sort_values("cosine", ascending=False))
guard_probe_df.to_csv(OUT_DIR / "lexical_guard_probe.csv", index=False)
print("Cap co cosine >= 0.90 nhung bi Lexical Guard chan:",
      guard_probe_df.query("cosine >= 0.90 and not guard_cho_gop")[["left", "right"]].values.tolist())

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 2188.56it/s]

audit rows: 23 | triples sau canonical: 271
{'REJECT_THRESHOLD': 17, 'MERGE_MANUAL': 3, 'MERGE_VECTOR': 3}

,type,left,right,similarity,decision,lexical_ratio
0,Company,HPE,Hewlett Packard Enterprise,1.000000,MERGE_MANUAL,NaN
1,Company,Dell,Dell Technologies,1.000000,MERGE_MANUAL,NaN
2,Company,Meta Platforms Inc,Meta,1.000000,MERGE_MANUAL,NaN
8,Company,Cumulus Technology Services Inc,Cumulus Technology Services Inc.,0.994372,MERGE_VECTOR,1.000
5,Company,Amazon Web Services,Amazon Web Services (AWS),0.928739,MERGE_VECTOR,0.905
3,Company,L&T Technology Services Limited,L&T Technology Services,0.925773,MERGE_VECTOR,1.000
7,Company,Synergy Quantum,Synergy Quantum India,0.867454,REJECT_THRESHOLD,0.833
14,Technology,generative AI,Generative AI Solutions,0.866633,REJECT_THRESHOLD,0.722
15,Technology,generative AI,Generative AI Capabilities,0.856484,REJECT_THRESHOLD,0.667
4,Company,Synopsys,Synopsys Inc.,0.832365,REJECT_THRESHOLD,1.000
10,Technology,cloud computing,cloud services,0.830391,REJECT_THRESHOLD,0.483
6,Company,Amazon Web Services,Amazon Web Services Inc.,0.823628,REJECT_THRESHOLD,1.000
21,Technology,Now Assist Generative AI Capabilities,Generative AI Capabilities,0.796372,REJECT_THRESHOLD,0.825
11,Technology,Llama 2,Code Llama,0.783534,REJECT_THRESHOLD,0.588
19,Technology,generative AI solutions for manufacturing,Generative AI Solutions,0.781076,REJECT_THRESHOLD,0.719
12,Technology,ChatGPT,OpenAI's ChatGPT,0.773496,REJECT_THRESHOLD,0.609
22,Technology,SAP CRM Sales,SAP CRM Service Manager,0.773034,REJECT_THRESHOLD,0.611
20,Technology,Generative AI Solutions,Generative AI Capabilities,0.773009,REJECT_THRESHOLD,0.735
16,Technology,generative AI,Generative AI offerings,0.766575,REJECT_THRESHOLD,0.722
17,Technology,Generative AI offerings,Generative AI Capabilities,0.759788,REJECT_THRESHOLD,0.653

,threshold,audit_rows,MERGE_VECTOR,REJECT_GUARD,MERGE_MANUAL,so_entity_canonical
0,0.80,23,7,2,3,387
1,0.85,23,5,1,3,389
2,0.90,23,3,0,3,391
3,0.95,23,1,0,3,393

,left,right,cosine,lexical_ratio,guard_cho_gop,ket_qua
9,Synopsys,Synopsys Inc.,0.832,1.000,True,REJECT_THRESHOLD
2,Sam Altman,Steve Altman,0.824,0.727,True,REJECT_THRESHOLD
8,Dell,Dell Technologies,0.821,0.381,False,REJECT_THRESHOLD
5,Llama 2,Code Llama,0.784,0.588,False,REJECT_THRESHOLD
1,Apple,Apple Inc.,0.735,1.000,True,REJECT_THRESHOLD
7,Microsoft,Microsoft Azure,0.650,0.750,True,REJECT_THRESHOLD
6,Amazon,Amazon Web Services,0.647,0.480,False,REJECT_THRESHOLD
0,Apple,Apple Watch,0.609,0.625,False,REJECT_THRESHOLD
3,Google,Google Cloud,0.546,0.667,False,REJECT_THRESHOLD
4,Meta,Meta Platforms Inc,0.511,0.444,False,REJECT_THRESHOLD

Cap co cosine >= 0.90 nhung bi Lexical Guard chan: []

In [10]:
#@title 2.3 — Node table + UNWIND bulk insert
def build_nodes(triples_df):
    rows = []
    for r in triples_df.itertuples(index=False):
        rows += [
            {"id":r.source_id,"name":r.source_name,"name_norm":r.source_name_norm,"type":r.source_type,"alias":r.source_raw},
            {"id":r.target_id,"name":r.target_name,"name_norm":r.target_name_norm,"type":r.target_type,"alias":r.target_raw},
        ]
    tmp = pd.DataFrame(rows)
    if tmp.empty:
        return tmp

    out = []
    for (node_id,name,name_norm,typ), g in tmp.groupby(["id","name","name_norm","type"]):
        aliases = sorted(set(g["alias"].map(norm_space)))
        out.append({
            "id":node_id, "name":name, "name_norm":name_norm, "type":typ,
            "aliases":aliases,
            "aliases_norm":sorted(set(norm_entity(x) for x in aliases))
        })
    return pd.DataFrame(out)

def batches(records, size=1000):
    for i in range(0, len(records), size):
        yield records[i:i+size]

def bulk_insert_nodes(nodes_df, batch_size=1000):
    for typ in sorted(ALLOWED_NODE_TYPES):
        part = nodes_df[nodes_df.type == typ]
        if part.empty:
            continue
        query = f"""
        UNWIND $rows AS row
        MERGE (n:Entity {{id: row.id}})
        SET n:{typ},
            n.name=row.name,
            n.name_norm=row.name_norm,
            n.entity_type=row.type,
            n.aliases=row.aliases,
            n.aliases_norm=row.aliases_norm
        """
        for b in batches(part.to_dict("records"), batch_size):
            run_cypher(query, rows=b)

def bulk_insert_edges(triples_df, batch_size=1000):
    required = {"source_chunk_id","published_date"}
    if not required.issubset(triples_df.columns):
        raise ValueError("Missing edge provenance.")

    for rel in sorted(ALLOWED_RELATIONS):
        part = triples_df[triples_df.relation == rel]
        if part.empty:
            continue

        query = f"""
        UNWIND $rows AS row
        MATCH (s:Entity {{id: row.source_id}})
        MATCH (t:Entity {{id: row.target_id}})
        MERGE (s)-[r:{rel} {{source_chunk_id: row.source_chunk_id}}]->(t)
        SET r.published_date=row.published_date,
            r.evidence=row.evidence,
            r.confidence=row.confidence
        """

        cols = ["source_id","target_id","source_chunk_id","published_date","evidence","confidence"]
        for b in batches(part[cols].to_dict("records"), batch_size):
            run_cypher(query, rows=b)

if RESET_GRAPH:
    run_cypher("MATCH (n) DETACH DELETE n")
    print("Da xoa graph cu (RESET_GRAPH=True) -> notebook idempotent khi Run All.")

nodes_df = build_nodes(triples_df)
print("nodes:", len(nodes_df), "| theo type:", nodes_df.type.value_counts().to_dict())

t0 = time.perf_counter()
bulk_insert_nodes(nodes_df)
bulk_insert_edges(triples_df)
print(f"Bulk insert xong (UNWIND, batch 1000) trong {time.perf_counter()-t0:.1f}s "
      f"cho {len(nodes_df)} node + {len(triples_df)} edge.")

Da xoa graph cu (RESET_GRAPH=True) -> notebook idempotent khi Run All.

nodes: 393 | theo type: {'Company': 257, 'Technology': 107, 'Person': 29}

Bulk insert xong (UNWIND, batch 1000) trong 0.9s cho 393 node + 271 edge.

In [11]:
#@title 2.4 — Sanity checks
def graph_checks():
    invalid = run_cypher("""
    MATCH ()-[r]->()
    WHERE r.source_chunk_id IS NULL OR r.published_date IS NULL
    RETURN count(r) AS n
    """)[0]["n"]

    counts = {
        "nodes": run_cypher("MATCH (n:Entity) RETURN count(n) AS n")[0]["n"],
        "edges": run_cypher("MATCH ()-[r]->() RETURN count(r) AS n")[0]["n"],
        "invalid_provenance_edges": invalid,
    }
    print(counts)
    assert invalid == 0

    top = pd.DataFrame(run_cypher("""
    MATCH (n:Entity)
    OPTIONAL MATCH (n)-[r]-()
    WITH n, count(r) AS degree
    RETURN n.id AS id, n.name AS name, n.entity_type AS type, degree
    ORDER BY degree DESC LIMIT 15
    """))
    display(top)
    return counts, top

graph_counts, top_degree_df = graph_checks()

# Cypher check goc chi bat NULL -> bo sung check CHUOI RONG.
# Neu published_date = "" thi ORDER BY published_date DESC cua super-node mitigation vo nghia.
empty_check = run_cypher("""
MATCH ()-[r]->()
RETURN count(r) AS total,
       sum(CASE WHEN r.source_chunk_id IS NULL OR r.source_chunk_id = '' THEN 1 ELSE 0 END) AS bad_chunk,
       sum(CASE WHEN r.published_date  IS NULL OR r.published_date  = '' THEN 1 ELSE 0 END) AS bad_date
""")[0]
print("Provenance check (ke ca chuoi rong):", empty_check)
assert empty_check["bad_chunk"] == 0 and empty_check["bad_date"] == 0
print("Max degree thuc te:", int(top_degree_df.degree.max()) if len(top_degree_df) else 0)

{'nodes': 393, 'edges': 271, 'invalid_provenance_edges': 0}

                          id                     name        type  degree
0   fb0f4df56fab164ec48722f0                Microsoft     Company      21
1   68b3544368862fc263941c8d                   Amazon     Company      12
2   7b29988cfc0dac3059f47a0e  L&T Technology Services     Company       7
3   cc9c6ee3857729e221d3f6de               ServiceNow     Company       7
4   70c4e949ff245096c6946802      Amazon Web Services     Company       7
5   110cfb16be66531da841ce26                   Thales     Company       6
6   4a992388a70cd573ed2b4d6b                    Falco  Technology       5
7   261c78e541bbb8921217639a                 Qualcomm     Company       5
8   0e132222d1315530d6efca52                   Google     Company       5
9   773eeb9b7cc008bff365fcdd                   OpenAI     Company       5
10  909fcd9c188c8c2429afa468             Google Cloud     Company       5
11  7c006ebf3fc788f4d55aae68                  Samsung     Company       4
12  7c277a3c91446bd00b58078d              Cloudbankin     Company       3
13  24efe6cedc09a12ec8c3eff2                 Synopsys     Company       3
14  3bd246d63c5fc107fabe9fd2            VIQ Solutions     Company       3

Provenance check (ke ca chuoi rong): {'total': 271, 'bad_chunk': 0, 'bad_date': 0}
Max degree thuc te: 21

# PHẦN 3 — FLAT RAG & HYBRID GRAPHRAG (45–75')

## Flat RAG baseline
Dùng cùng embedding/generator để comparison tập trung vào retrieval architecture.

In [12]:
#@title 3.1 — Flat RAG
flat_index = None
flat_store = None
entity_match_vectors = None
entity_match_store = None

def build_flat_index(chunks_df):
    global flat_index, flat_store
    vecs = get_embedder().encode(
        chunks_df.text.fillna("").tolist(),
        batch_size=128, show_progress_bar=True,
        normalize_embeddings=True
    ).astype("float32")

    flat_index = faiss.IndexFlatIP(vecs.shape[1])
    flat_index.add(vecs)
    flat_store = chunks_df.reset_index(drop=True).copy()
    print("Flat vectors:", flat_index.ntotal)

def retrieve_flat_context(query, k=6):
    qv = get_embedder().encode(
        [query], normalize_embeddings=True, show_progress_bar=False
    ).astype("float32")
    scores, ids = flat_index.search(qv, min(k, flat_index.ntotal))

    rows = []
    for score, idx in zip(scores[0], ids[0]):
        if idx < 0:
            continue
        r = flat_store.iloc[int(idx)]
        rows.append({
            "score":float(score), "chunk_id":r.chunk_id,
            "published_date":r.published_date, "text":r.text
        })

    df = pd.DataFrame(rows)
    context = "\n\n".join(
        f"[chunk_id={r.chunk_id} | date={r.published_date} | score={r.score:.3f}]\n{r.text}"
        for r in df.itertuples(index=False)
    )
    return context, df

build_flat_index(chunks_df)
print("Flat RAG index san sang | vectors:", flat_index.ntotal, "| dim:", flat_index.d)

Batches:   0%|          | 0/17 [00:00<?, ?it/s]

Batches:   6%|▌         | 1/17 [00:10<02:54, 10.92s/it]

Batches:  12%|█▏        | 2/17 [00:14<01:42,  6.84s/it]

Batches:  18%|█▊        | 3/17 [00:21<01:31,  6.54s/it]

Batches:  24%|██▎       | 4/17 [00:26<01:18,  6.00s/it]

Batches:  29%|██▉       | 5/17 [00:30<01:03,  5.30s/it]

Batches:  35%|███▌      | 6/17 [00:36<01:03,  5.74s/it]

Batches:  41%|████      | 7/17 [00:40<00:49,  4.93s/it]

Batches:  47%|████▋     | 8/17 [00:43<00:40,  4.49s/it]

Batches:  53%|█████▎    | 9/17 [00:48<00:36,  4.53s/it]

Batches:  59%|█████▉    | 10/17 [00:52<00:31,  4.52s/it]

Batches:  65%|██████▍   | 11/17 [00:56<00:25,  4.28s/it]

Batches:  71%|███████   | 12/17 [01:01<00:22,  4.47s/it]

Batches:  76%|███████▋  | 13/17 [01:05<00:17,  4.26s/it]

Batches:  82%|████████▏ | 14/17 [01:08<00:11,  3.88s/it]

Batches:  88%|████████▊ | 15/17 [01:11<00:07,  3.58s/it]

Batches:  94%|█████████▍| 16/17 [01:13<00:03,  3.21s/it]

Batches: 100%|██████████| 17/17 [01:14<00:00,  2.59s/it]

Batches: 100%|██████████| 17/17 [01:14<00:00,  4.39s/it]

Flat vectors: 2114
Flat RAG index san sang | vectors: 2114 | dim: 384

## Graph retrieval flow
1. LLM trích seed entities.
2. Match seed trong Neo4j; fuzzy fallback bằng embedding.
3. BFS tối đa `max_hops`.
4. Nếu node degree > 100 → chỉ lấy tối đa 50 edge mới nhất.
5. Global edge cap để tránh context explosion.
6. Textualize subgraph có provenance.

In [13]:
#@title 3.2 — Seed matching (exact -> lexical -> vector fallback)
SEED_SYSTEM = """
Extract useful seed entities for graph retrieval.
Allowed types: Company, Person, Technology.
Include both the full name and any acronym/short form that appears in the question.
Do not answer the question. Return strict JSON only.
""".strip()

def extract_seeds(query):
    obj, _ = gen_json(SEED_SYSTEM, f"""
Question: {query}
Return a json object: {{"seeds":[{{"name":"...","type":"Company|Person|Technology|null"}}]}}
""", tag="seed")
    return [
        {"name": norm_space(x.get("name")),
         "type": x.get("type") if x.get("type") in ALLOWED_NODE_TYPES else None}
        for x in obj.get("seeds", [])
        if norm_space(x.get("name"))
    ]

def build_entity_matcher(nodes_df):
    global entity_match_vectors, entity_match_store
    entity_match_store = nodes_df.reset_index(drop=True).copy()
    entity_match_vectors = get_embedder().encode(
        entity_match_store.name.tolist(),
        batch_size=128, show_progress_bar=False,
        normalize_embeddings=True
    ).astype("float32")

EXACT_SEED_CYPHER = """
MATCH (n:Entity)
WHERE (n.name_norm=$name OR $name IN coalesce(n.aliases_norm,[]))
  AND ($typ IS NULL OR n.entity_type=$typ)
RETURN n.id AS id, n.name AS name, n.entity_type AS type
LIMIT 5
"""

# Tang 2 — khop tu vung: "Dell" phai cham duoc node "Dell Technologies".
# Chi chap nhan khi seed >= 4 ky tu de tranh khop rac ("AI", "IT" khop moi thu).
LEXICAL_SEED_CYPHER = """
MATCH (n:Entity)
WHERE ($typ IS NULL OR n.entity_type=$typ)
  AND (n.name_norm STARTS WITH $name OR $name STARTS WITH n.name_norm
       OR n.name_norm CONTAINS $name)
RETURN n.id AS id, n.name AS name, n.entity_type AS type, size(n.name_norm) AS len
ORDER BY len ASC
LIMIT 3
"""

def match_seeds(query, fuzzy_threshold=0.66, return_debug=False):
    """3 tang: exact (name/alias) -> lexical containment -> vector ANN.
    Ghi lai tang nao giai duoc seed nao de truy nguyen ca hong 'NO_SEED'."""
    matched, debug = [], []
    for seed in extract_seeds(query):
        key = norm_entity(seed["name"])

        exact = run_cypher(EXACT_SEED_CYPHER, name=key, typ=seed["type"])
        if exact:
            matched += exact
            debug.append({"seed": seed["name"], "route": "EXACT", "hit": exact[0]["name"]})
            continue

        if len(key) >= 4:
            lex = run_cypher(LEXICAL_SEED_CYPHER, name=key, typ=seed["type"])
            if lex:
                matched += [{k: r[k] for k in ("id", "name", "type")} for r in lex[:1]]
                debug.append({"seed": seed["name"], "route": "LEXICAL", "hit": lex[0]["name"]})
                continue

        if entity_match_vectors is None:
            debug.append({"seed": seed["name"], "route": "NO_MATCH", "hit": None})
            continue

        mask = np.ones(len(entity_match_store), dtype=bool)
        if seed["type"]:
            mask = entity_match_store.type.eq(seed["type"]).to_numpy()
        idxs = np.flatnonzero(mask)
        if not len(idxs):
            debug.append({"seed": seed["name"], "route": "NO_MATCH", "hit": None})
            continue

        qv = get_embedder().encode(
            [seed["name"]], normalize_embeddings=True, show_progress_bar=False
        ).astype("float32")[0]
        sims = entity_match_vectors[idxs] @ qv
        j = int(np.argmax(sims))
        if float(sims[j]) >= fuzzy_threshold:
            r = entity_match_store.iloc[int(idxs[j])]
            matched.append({"id": r.id, "name": r["name"], "type": r.type})
            debug.append({"seed": seed["name"], "route": "VECTOR",
                          "hit": r["name"], "sim": round(float(sims[j]), 3)})
        else:
            debug.append({"seed": seed["name"], "route": "BELOW_THRESHOLD",
                          "hit": entity_match_store.iloc[int(idxs[j])]["name"],
                          "sim": round(float(sims[j]), 3)})

    uniq = list({x["id"]: x for x in matched}.values())
    return (uniq, debug) if return_debug else uniq

build_entity_matcher(nodes_df)
print("Entity matcher san sang | nodes:", len(nodes_df))
_seeds, _dbg = match_seeds("What did HPE acquire in 2023?", return_debug=True)
print("Thu seed resolution:", _dbg)

Entity matcher san sang | nodes: 393

Thu seed resolution: [{'seed': 'HPE', 'route': 'EXACT', 'hit': 'Hewlett Packard Enterprise'}]

In [14]:
#@title 3.3 — Graph traversal + super-node mitigation
SUPER_NODE_DEGREE = 100        # bac vuot nguong nay bi coi la super-node
SUPER_NODE_EDGE_CAP = 50       # chi lay 50 canh MOI NHAT cua super-node
GLOBAL_EDGE_CAP = 250          # tran canh cho toan bo mot lan truy van
MAX_GRAPH_CONTEXT_CHARS = 14000  # tran do dai context do thi (chan token explosion)

def node_degree(node_id):
    return int(run_cypher("""
    MATCH (n:Entity {id:$id})
    OPTIONAL MATCH (n)-[r]-()
    RETURN count(r) AS degree
    """, id=node_id)[0]["degree"])

def recent_edges(node_id, limit):
    """Lay canh cua node, UU TIEN published_date moi nhat — day chinh la chinh sach
    cat tia super-node: giu thong tin thoi su, bo lich su cu."""
    return run_cypher("""
    MATCH (n:Entity {id:$id})
    MATCH (n)-[r]-(m:Entity)
    RETURN
      startNode(r).id AS source_id,
      startNode(r).name AS source_name,
      startNode(r).entity_type AS source_type,
      type(r) AS relation,
      endNode(r).id AS target_id,
      endNode(r).name AS target_name,
      endNode(r).entity_type AS target_type,
      r.source_chunk_id AS source_chunk_id,
      r.published_date AS published_date,
      r.evidence AS evidence,
      m.id AS neighbor_id
    ORDER BY coalesce(r.published_date,'') DESC
    LIMIT $limit
    """, id=node_id, limit=int(limit))

def textualize(edges):
    edges = sorted(edges, key=lambda e: e.get("published_date") or "", reverse=True)
    lines, used = [], 0
    for e in edges:
        line = (
            f"{e['source_name']} [{e['source_type']}] -{e['relation']}-> "
            f"{e['target_name']} [{e['target_type']}] "
            f"| date={e.get('published_date') or 'unknown'} "
            f"| chunk={e.get('source_chunk_id') or 'unknown'}"
        )
        if e.get("evidence"):
            line += f" | evidence={norm_space(e['evidence'])}"
        if used + len(line) + 1 > MAX_GRAPH_CONTEXT_CHARS:
            break
        lines.append(line)
        used += len(line) + 1
    return "\n".join(lines)

def retrieve_graph_context(query, max_hops=2, edge_limit=50, return_debug=False):
    seeds, seed_debug = match_seeds(query, return_debug=True)
    if not seeds:
        out = {"context": "", "edges": pd.DataFrame(),
               "diagnostics": {"reason": "NO_SEED", "matched_seeds": [],
                               "seed_debug": seed_debug, "expanded_nodes": 0,
                               "collected_edges": 0, "supernode_events": []}}
        return out if return_debug else ""

    frontier = deque((x["id"], 0) for x in seeds)
    expanded, seen_edges, collected = set(), set(), []
    supernode_events = []

    while frontier and len(collected) < GLOBAL_EDGE_CAP:
        node_id, hop = frontier.popleft()
        if node_id in expanded or hop >= max_hops:
            continue
        expanded.add(node_id)

        degree = node_degree(node_id)
        limit = int(edge_limit)
        if degree > SUPER_NODE_DEGREE:
            limit = min(limit, SUPER_NODE_EDGE_CAP)
            supernode_events.append({"node_id": node_id, "degree": degree, "limit": limit})

        for e in recent_edges(node_id, limit):
            key = (e["source_id"], e["relation"], e["target_id"], e["source_chunk_id"])
            if key in seen_edges:
                continue
            seen_edges.add(key)
            collected.append(e)
            if len(collected) >= GLOBAL_EDGE_CAP:
                break

            nb = e.get("neighbor_id")
            if nb and nb not in expanded and hop + 1 < max_hops:
                frontier.append((nb, hop + 1))

    out = {
        "context": textualize(collected),
        "edges": pd.DataFrame(collected),
        "diagnostics": {
            "reason": "OK",
            "matched_seeds": seeds,
            "seed_debug": seed_debug,
            "expanded_nodes": len(expanded),
            "collected_edges": len(collected),
            "supernode_events": supernode_events,
        }
    }
    return out if return_debug else out["context"]

In [15]:
#@title 3.4 — Flat answer vs Hybrid GraphRAG answer
ANSWER_SYSTEM = """
Answer only from supplied context.
Be concise but complete. Do not invent facts.
Cite provenance inline as [chunk_id=...] whenever possible.
If evidence is insufficient or conflicting, say so.
""".strip()

def generate_answer(question, context):
    prompt = f"QUESTION:\n{question}\n\nCONTEXT:\n{context}\n\nANSWER:"
    t0 = time.perf_counter()
    text, usage = gen_chat(
        [{"role": "system", "content": ANSWER_SYSTEM},
         {"role": "user", "content": prompt}],
        tag="answer",
    )
    return {
        "answer": text.strip(),
        "latency_s": time.perf_counter()-t0,
        "total_tokens": usage.get("total_tokens"),
    }

def answer_flat_rag(question):
    context, retrieved = retrieve_flat_context(question, k=6)
    out = generate_answer(question, context)
    out.update({"context":context,"retrieved":retrieved})
    return out

def answer_graph_rag(question):
    g = retrieve_graph_context(question, max_hops=2, edge_limit=50, return_debug=True)
    vctx, vdocs = retrieve_flat_context(question, k=4)
    context = f"=== GRAPH ===\n{g['context']}\n\n=== VECTOR ===\n{vctx}"
    out = generate_answer(question, context)
    out.update({"context":context,"graph_debug":g,"vector_docs":vdocs})
    return out

print("Generator:", GEN_PROVIDER, GEN_MODEL, "| dung CHUNG cho ca Flat RAG va GraphRAG")

Generator: openai gpt-4o-mini | dung CHUNG cho ca Flat RAG va GraphRAG

In [16]:
#@title 3.5 — Smoke test 1 cau truoc khi chay evaluation hang loat
q = "Which company did HPE agree to acquire to expand edge-to-cloud security?"   # G5000-41 (factoid)

g = retrieve_graph_context(q, max_hops=2, edge_limit=50, return_debug=True)
print("seeds:", g["diagnostics"]["matched_seeds"])
print("expanded:", g["diagnostics"]["expanded_nodes"],
      "| edges:", g["diagnostics"]["collected_edges"],
      "| supernode_events:", g["diagnostics"]["supernode_events"])
print("-" * 70)
print(g["context"][:800] or "(GRAPH CONTEXT RONG -> seed khong match, xem danh sach node duoi day)")

if not g["diagnostics"].get("matched_seeds"):
    display(pd.DataFrame(run_cypher(
        "MATCH (n:Entity) RETURN n.name AS name, n.entity_type AS type ORDER BY name LIMIT 60")))
else:
    print("=" * 30, "FLAT RAG", "=" * 30)
    print(answer_flat_rag(q)["answer"][:600])
    print("=" * 30, "HYBRID GRAPHRAG", "=" * 30)
    print(answer_graph_rag(q)["answer"][:600])

seeds: [{'id': '51e33a1bf5fff64b108c76e6', 'name': 'Hewlett Packard Enterprise', 'type': 'Company'}]
expanded: 3 | edges: 2 | supernode_events: []
----------------------------------------------------------------------
Hewlett Packard Enterprise [Company] -USES-> supercomputers [Technology] | date=2023-06-21 | chunk=row03289::c0000 | evidence=HPE to offer cloud computing service for artificial intelligence. The company will use its experience in supercomputers
Hewlett Packard Enterprise [Company] -ACQUIRED-> Axis Security [Company] | date=2023-03-02 | chunk=row04762::c0000 | evidence=Hewlett Packard Enterprise (NYSE: HPE) today announced that it entered into a definitive agreement to acquire Axis Security a cloud security provider.
============================== FLAT RAG ==============================

Hewlett Packard Enterprise (HPE) agreed to acquire Axis Security to expand its edge-to-cloud security capabilities [chunk_id=row04762::c0000].
============================== HYBRID GRAPHRAG ==============================

Hewlett Packard Enterprise (HPE) agreed to acquire Axis Security to expand its edge-to-cloud security capabilities [chunk_id=row04762::c0000].

# PHẦN 4 — GOLDEN DATASET & LLM-AS-A-JUDGE (75–105')

## Golden schema
`id`, `group`, `question`, `reference_answer`, optional `reference_evidence`.

Notebook có 5 câu starter. Các câu phụ thuộc data dump phải điền gold answer thật trước final evaluation.

In [17]:
#@title 4.0 — Doi chieu Golden Dataset voi graph (chay truoc 4.1)
# 3 truy van duoi kiem tra graph co du "hinh dang" de tra loi 3 nhom cau hoi hay khong:
# factoid (canh don co evidence), multi-hop (2 chang tu 2 chunk khac nhau), cross-doc (>=2 chunk).
print("=" * 26, "FACTOID: quan he don, confidence cao", "=" * 26)
display(pd.DataFrame(run_cypher("""
MATCH (a:Entity)-[r]->(b:Entity)
WHERE r.evidence IS NOT NULL AND size(r.evidence) > 40
RETURN a.name AS src, type(r) AS rel, b.name AS dst,
       r.published_date AS date, r.source_chunk_id AS chunk,
       r.confidence AS conf, left(r.evidence, 90) AS ev
ORDER BY r.confidence DESC LIMIT 15
""")))

print("=" * 26, "MULTI-HOP: 2 chang tu 2 CHUNK KHAC NHAU", "=" * 26)
multihop_paths_df = pd.DataFrame(run_cypher("""
MATCH (a:Entity)-[r1]->(m:Entity)-[r2]->(c:Entity)
WHERE a <> c AND r1.source_chunk_id <> r2.source_chunk_id
RETURN a.name AS a, type(r1) AS rel1, m.name AS mid, type(r2) AS rel2, c.name AS c,
       r1.source_chunk_id AS chunk1, r2.source_chunk_id AS chunk2
LIMIT 20
"""))
display(multihop_paths_df)
print("So duong multi-hop noi 2 tai lieu khac nhau (mau 20 dong o tren):", len(multihop_paths_df))

print("=" * 26, "CROSS-DOC: cung cap entity, >= 2 chunk", "=" * 26)
display(pd.DataFrame(run_cypher("""
MATCH (a:Entity)-[r]->(b:Entity)
WITH a, b, type(r) AS rel,
     collect(DISTINCT r.source_chunk_id) AS chunks,
     collect(DISTINCT r.published_date)  AS dates
WHERE size(chunks) >= 2
RETURN a.name AS a, rel, b.name AS b, size(chunks) AS n_chunks, dates
ORDER BY n_chunks DESC LIMIT 15
""")))

========================== FACTOID: quan he don, confidence cao ==========================

,src,rel,dst,date,chunk,conf,ev
0,Thales,USES,L&T Technology Services,2023-02-23,row03296::c0000,1.0,L&T Technology Services and Qualcomm Selected by Thales
1,PreCheck Health Services,USES,Pierian,2022-12-06,row02334::c0000,1.0,Pierian Selected by PreCheck Health Services to Support Hereditary Cancer Testing for Prov
2,TRG,ACQUIRED,Symec Technologies Limited,2023-04-06,row01363::c0000,1.0,TRG Expands UK and European Operations with Acquisition of Symec Technologies. TRG a globa
3,GreenPages,ACQUIRED,Zanaris,2023-05-02,row00003::c0000,1.0,In February GreenPages acquired Toronto-based Zanaris an IT automation cloud and DevOps se
4,Thales,USES,5G private networks,2023-02-23,row00891::c0000,1.0,Enabling 5G Private Networks in Urban Railways
5,WatchGuard Technologies,ACQUIRED,CyGlass Technology Services,2023-09-20,row02851::c0000,1.0,WatchGuard Technologies announces acquisition of CyGlass Technology Services
6,WatchGuard Technologies,USES,CyGlass technology,2023-09-20,row02851::c0000,1.0,The CyGlass technology will add to the WatchGuard Unified Security Platform architecture d
7,Google,DEVELOPED,DataCenter,2023-05-08,row03400::c0000,1.0,Google announces plans to build two more data centers in Columbus and Lancaster
8,Google,DEVELOPED,unknown tracker alerts,2023-08-10,row02840::c0000,1.0,Google has introduced a convenient way to identify an unknown tracker using an Android sma
9,Google,DEVELOPED,Bard AI,2023-10-03,row01863::c0000,1.0,Google on Tuesday added newer capabilities to its generative AI service Bard
10,Google,DEVELOPED,Gemini,2023-09-15,row03943::c0000,1.0,Alphabet's (GOOGL.O) Google has given a small group of companies access to an early versio
11,Comcast Technology Solutions,DEVELOPED,Managed Channel Origination service,2023-09-13,row02818::c0000,1.0,Comcast Technology Solutions (CTS) today announced the launch of a new cloud-based Managed
12,Associated Press,PARTNERED_WITH,OpenAI,2023-07-13,row00366::c0000,1.0,AP Open AI agree to share select news content and technology in new collaboration
13,Thales,USES,Qualcomm,2023-02-23,row03296::c0000,1.0,L&T Technology Services and Qualcomm Selected by Thales
14,Keysight,PARTNERED_WITH,Synopsys,2023-09-21,row00272::c0000,1.0,Keysight and Synopsys Partner for IoT Device Cybersecurity

========================== MULTI-HOP: 2 chang tu 2 CHUNK KHAC NHAU ==========================

,a,rel1,mid,rel2,c,chunk1,chunk2
0,L&T Technology Services,PARTNERED_WITH,Thales,USES,Qualcomm,row00261::c0000,row03296::c0000
1,L&T Technology Services,PARTNERED_WITH,Thales,USES,Qualcomm,row00891::c0000,row03296::c0000
2,Qualcomm,PARTNERED_WITH,Thales,USES,L&T Technology Services,row00891::c0000,row03296::c0000
3,L&T Technology Services,PARTNERED_WITH,Thales,USES,5G private networks,row00261::c0000,row00891::c0000
4,Keysight,PARTNERED_WITH,Synopsys,DEVELOPED,IC Design Workforce,row00272::c0000,row01505::c0000
5,Keysight,PARTNERED_WITH,Synopsys,DEVELOPED,ZeBu Server 5 Emulation System,row00272::c0000,row01424::c0000
6,L&T Technology Services,PARTNERED_WITH,Qualcomm,PARTNERED_WITH,Campina Grande's City Hall,row00891::c0000,row04002::c0000
7,Thales,USES,Qualcomm,PARTNERED_WITH,Campina Grande's City Hall,row03296::c0000,row04002::c0000
8,L&T Technology Services,PARTNERED_WITH,Qualcomm,PARTNERED_WITH,MTM Technology,row00891::c0000,row04002::c0000
9,Thales,USES,Qualcomm,PARTNERED_WITH,MTM Technology,row03296::c0000,row04002::c0000
10,Netflix,USES,Amazon,DEVELOPED,Healthcare system for generating clinical notes,row02190::c0000,row02532::c0000
11,Netflix,USES,Amazon,DEVELOPED,Healthcare system for generating clinical notes,row02190::c0000,row02537::c0000
12,Netflix,USES,Amazon,DEVELOPED,DataCenter,row02190::c0000,row03400::c0000
13,Netflix,USES,Amazon,DEVELOPED,Conversational customer-service agents technology,row02190::c0000,row02532::c0000
14,Netflix,USES,Amazon,DEVELOPED,Conversational customer-service agents technology,row02190::c0000,row02537::c0000
15,Netflix,USES,Amazon,PARTNERED_WITH,Cohere,row02190::c0000,row02532::c0000
16,Netflix,USES,Amazon,PARTNERED_WITH,Cohere,row02190::c0000,row02537::c0000
17,Netflix,USES,Amazon,USES,Falco,row02190::c0000,row03442::c0000
18,Netflix,USES,Amazon,USES,cloud services,row02190::c0000,row01662::c0000
19,Netflix,USES,Amazon,INVESTED_IN,AI education program,row02190::c0000,row03429::c0000

So duong multi-hop noi 2 tai lieu khac nhau (mau 20 dong o tren): 20
========================== CROSS-DOC: cung cap entity, >= 2 chunk ==========================

,a,rel,b,n_chunks,dates
0,Apogee,ACQUIRED,Cumulus Technology Services Inc,2,"[2022-12-16, 2023-01-07]"
1,Infineon,PARTNERED_WITH,Resonac,2,[2023-01-12]
2,Amazon,DEVELOPED,Healthcare system for generating clinical notes,2,"[2023-07-26, 2023-07-27]"
3,Amazon,DEVELOPED,Conversational customer-service agents technology,2,"[2023-07-26, 2023-07-27]"
4,Amazon,PARTNERED_WITH,Cohere,2,"[2023-07-26, 2023-07-27]"
5,Truescope,ACQUIRED,Universal Information Services,2,[2023-02-01]
6,L&T Technology Services,PARTNERED_WITH,Thales,2,[2023-02-23]
7,Alight Inc.,DEVELOPED,behavioral health navigation services,2,[2023-06-08]
8,ServiceNow,PARTNERED_WITH,NVIDIA,2,"[2023-05-17, 2023-07-27]"
9,Microsoft,DEVELOPED,Copilot,2,"[2023-09-21, 2023-03-17]"

In [18]:
#@title 4.1 — Golden Dataset (25 cau, xay tren dung 5.000 dong dau)
# KHONG dung 5 cau starter G01-G05 cua code khung: chung duoc viet truoc, khong dua tren subset
# dang nap (vd "CEO of Hugging Face 2023" khong co trong corpus) -> ca 2 kien truc cung sai,
# benchmark vo nghia. Thay bang bo golden 25 cau da xay tren dung scope 5.000 dong dau,
# moi cau co evidence_row_ids_0based tro thang ve dong du lieu goc -> kiem chung duoc.
golden_full_df = pd.read_csv(GOLDEN_SRC)

golden_df = golden_full_df[["id", "group", "question", "reference_answer", "reference_evidence"]].copy()
golden_df.to_csv(GOLDEN_PATH, index=False)

# Map cau hoi -> tap chunk_id bang chung (dung do Retrieval Evidence Recall o cell 4.3)
golden_evidence_chunks = {
    r.id: {"row%05d::c0000" % int(i) for i in json.loads(r.evidence_row_ids_0based)}
    for r in golden_full_df.itertuples(index=False)
}

print("Golden Dataset:", len(golden_df), "cau |", golden_df.group.value_counts().to_dict())
print("expected_hops:", golden_full_df.expected_hops.value_counts().to_dict())
print("So cau co toan bo chunk bang chung nam trong graph:",
      sum(1 for qid, ch in golden_evidence_chunks.items()
          if ch <= set(extraction_source.chunk_id)), "/", len(golden_evidence_chunks))
display(golden_df.head(8))

def validate_golden(df, require_answers=True):
    required = {"id", "group", "question", "reference_answer"}
    if not required.issubset(df.columns):
        raise ValueError(f"Missing columns: {required-set(df.columns)}")
    if require_answers and df.reference_answer.fillna("").str.strip().eq("").any():
        display(df[df.reference_answer.fillna("").str.strip().eq("")][["id", "question"]])
        raise ValueError("Dien reference_answer truoc final evaluation.")
    if set(df.group.unique()) < {"factoid", "multi-hop", "cross-doc"}:
        raise ValueError("Golden set phai phu du 3 nhom factoid / multi-hop / cross-doc.")
    print("Golden Dataset valid — du 3 nhom, khong con reference_answer trong.")

Golden Dataset: 25 cau | {'multi-hop': 12, 'cross-doc': 11, 'factoid': 2}
expected_hops: {2: 15, 3: 7, 1: 2, 4: 1}
So cau co toan bo chunk bang chung nam trong graph: 25 / 25

,id,group,question,reference_answer,reference_evidence
0,G5000-26,multi-hop,"What external technology provider is named inside Amazon's July AI-service expansion, and what other new AI capabili...",Amazon's AI-service story names access to technology from Cohere. It also mentions a program for building more conve...,row 2532 (2023-07-26 20:19:00): Exclusive: Amazon has drawn thousands to try its AI service competing with Microsoft...
1,G5000-27,cross-doc,How should the graph reconcile the statement that AMD powers multiple cloud services with the later Reuters report a...,The June 1 investment article broadly says AMD powers multiple cloud services through its chips. The June 14 Reuters...,row 3357 (2023-06-01 13:16:00): 3 Best Cloud Stocks to Buy in June | row 2905 (2023-06-14 08:47:00): Exclusive: Amaz...
2,G5000-28,multi-hop,"Which model providers are connected to Google Cloud Next '23 in the selected data, and which models are associated w...",Meta is connected via Llama 2 and Code Llama; the Technology Innovation Institute is connected via Falcon LLM; Anthr...,row 3395 (2023-08-29 18:07:00): Google Cloud Kicks Off Next '23 with a New Way to Cloud
3,G5000-29,cross-doc,How did participation in White House AI commitments broaden from July to September 2023 according to the selected re...,"The July report names seven companies including Google, Meta, and OpenAI as making voluntary AI commitments. The Sep...",row 3380 (2023-07-21 13:01:00): The White House and big tech companies release commitments on managing AI | row 3330...
4,G5000-30,multi-hop,"Meta appears in two different AI contexts in the selected data. What are they, and what distinct relation should the...","At Google Cloud Next, Meta is the provider/source of Llama 2 and Code Llama models made available on Google Cloud. S...",row 3395 (2023-08-29 18:07:00): Google Cloud Kicks Off Next '23 with a New Way to Cloud | row 3380 (2023-07-21 13:01...
5,G5000-31,multi-hop,"Order OpenAI's ecosystem moves from March through July 2023 using the selected sources: plug-ins, open-source model ...",March: ChatGPT gained support for about a dozen application plug-ins. May: OpenAI was reported to be preparing a new...,row 3938 (2023-03-24 15:58:00): OpenAI's ChatGPT gets support for a dozen application plug-ins | row 946 (2023-05-15...
6,G5000-32,cross-doc,What is the difference between OpenAI's March plug-in development and its June reported app-store plan?,The March story describes ChatGPT gaining support for application plug-ins so companies can expose product functiona...,row 3938 (2023-03-24 15:58:00): OpenAI's ChatGPT gets support for a dozen application plug-ins | row 2449 (2023-06-2...
7,G5000-33,cross-doc,"Which July OpenAI-related event is a content/technology collaboration, and which July event is a voluntary governanc...",The AP–OpenAI agreement is a collaboration to share access to select news content and technology for generative-AI u...,row 366 (2023-07-13 00:00:00): AP Open AI agree to share select news content and technology in new collaboration | r...

In [19]:
#@title 4.2 — LLM-as-a-Judge
JUDGE_SYSTEM = """
You are a strict evaluator of RAG answers. Return strict JSON only.
Score each dimension 1-5:
- comprehensiveness: does the answer cover every entity/aspect the question asks for?
- faithfulness: is every claim supported by the supplied candidate context? Penalise unsupported claims hard.
- multi_hop_reasoning: are the required reasoning hops (and their order/dates) correct?
Use the reference answer as the correctness anchor. Missing hops => low multi_hop score.
""".strip()

def judge_json(system, user, max_retries=4):
    if not JUDGE_MODEL:
        raise RuntimeError("Thieu JUDGE_MODEL.")

    if JUDGE_PROVIDER == "groq":
        return groq_json(system, user, model=JUDGE_MODEL)[0]

    if JUDGE_PROVIDER == "openai":
        if not OPENAI_API_KEY:
            raise RuntimeError("Thieu OPENAI_API_KEY.")
        from openai import OpenAI
        client = OpenAI(api_key=OPENAI_API_KEY)
        last = None
        for attempt in range(max_retries):
            try:
                resp = client.chat.completions.create(
                    model=JUDGE_MODEL,
                    messages=[{"role": "system", "content": system},
                              {"role": "user", "content": user}],
                    temperature=0.0,
                    response_format={"type": "json_object"},
                )
                return parse_json_object(resp.choices[0].message.content)
            except Exception as e:
                last = e
                time.sleep(min(20, 2 ** attempt + random.random()))
        raise RuntimeError(last)

    raise ValueError("JUDGE_PROVIDER must be openai or groq.")

def judge_answer(question, reference, answer, context):
    prompt = f"""
QUESTION:
{question}

REFERENCE ANSWER (ground truth):
{reference}

CANDIDATE ANSWER:
{answer}

CANDIDATE CONTEXT (the only evidence the candidate system had):
{context[:18000]}

Return a json object exactly in this shape:
{{
 "comprehensiveness": 1,
 "faithfulness": 1,
 "multi_hop_reasoning": 1,
 "rationale": "2-5 sentences"
}}
"""
    obj = judge_json(JUDGE_SYSTEM, prompt)
    out = {}
    for k in ["comprehensiveness", "faithfulness", "multi_hop_reasoning"]:
        out[k] = max(1, min(5, int(obj.get(k, 1))))
    out["rationale"] = norm_space(obj.get("rationale"))
    return out

print("Judge san sang |", JUDGE_PROVIDER, JUDGE_MODEL)

Judge san sang | openai gpt-4o-mini

In [20]:
#@title 4.3 — Evaluation runner + checkpoint + Retrieval Evidence Recall
# Ngoai diem Judge (chu quan), do them 1 metric KHACH QUAN:
#   Evidence Recall = ty le chunk bang chung vang thuc su xuat hien trong context ma he thong lay ve.
# Metric nay tach bach loi RETRIEVAL voi loi GENERATION khi phan tich ca loi.
CHUNK_RE = re.compile(r"chunk=([A-Za-z0-9_:\-]+)")

def evidence_recall(gold_chunks, retrieved_chunks):
    if not gold_chunks:
        return np.nan
    return len(set(gold_chunks) & set(retrieved_chunks)) / len(set(gold_chunks))

TRACE_PATH = str(OUT_DIR / "eval_traces.json")

def run_evaluation(golden_df, resume=True):
    done_ids, rows = set(), []
    traces = json.load(open(TRACE_PATH, encoding="utf-8")) if Path(TRACE_PATH).exists() else {}
    if resume and Path(CHECKPOINT).exists():
        ck = pd.read_csv(CHECKPOINT)
        rows = ck.to_dict("records")
        done_ids = set(ck.id)
        print(f"[checkpoint] da co {len(done_ids)} cau -> chay tiep {len(golden_df)-len(done_ids)} cau")

    todo = golden_df[~golden_df.id.isin(done_ids)]
    for q in tqdm(todo.itertuples(index=False), total=len(todo), desc="Evaluation"):
        flat = answer_flat_rag(q.question)
        graph = answer_graph_rag(q.question)

        jf = judge_answer(q.question, q.reference_answer, flat["answer"], flat["context"])
        jg = judge_answer(q.question, q.reference_answer, graph["answer"], graph["context"])

        gold_chunks = golden_evidence_chunks.get(q.id, set())
        flat_chunks = set(flat["retrieved"].chunk_id) if len(flat["retrieved"]) else set()
        graph_edges = graph["graph_debug"]["edges"]
        graph_only_chunks = set(graph_edges.source_chunk_id) if len(graph_edges) else set()
        hybrid_chunks = graph_only_chunks | (set(graph["vector_docs"].chunk_id) if len(graph["vector_docs"]) else set())
        diag = graph["graph_debug"]["diagnostics"]

        rows.append({
            "id": q.id, "group": q.group, "question": q.question,
            "reference_answer": q.reference_answer,
            "flat_answer": flat["answer"], "graph_answer": graph["answer"],
            "flat_comprehensiveness": jf["comprehensiveness"],
            "graph_comprehensiveness": jg["comprehensiveness"],
            "flat_faithfulness": jf["faithfulness"],
            "graph_faithfulness": jg["faithfulness"],
            "flat_multi_hop_reasoning": jf["multi_hop_reasoning"],
            "graph_multi_hop_reasoning": jg["multi_hop_reasoning"],
            "flat_latency_s": round(flat["latency_s"], 3),
            "graph_latency_s": round(graph["latency_s"], 3),
            "flat_total_tokens": flat.get("total_tokens"),
            "graph_total_tokens": graph.get("total_tokens"),
            "flat_context_chars": len(flat["context"]),
            "graph_context_chars": len(graph["context"]),
            "flat_evidence_recall": evidence_recall(gold_chunks, flat_chunks),
            "graph_evidence_recall": evidence_recall(gold_chunks, hybrid_chunks),
            "graph_only_evidence_recall": evidence_recall(gold_chunks, graph_only_chunks),
            "gold_evidence_chunks": "|".join(sorted(gold_chunks)),
            "graph_matched_seeds": "|".join(s["name"] for s in diag.get("matched_seeds", [])),
            "graph_expanded_nodes": diag.get("expanded_nodes", 0),
            "graph_collected_edges": diag.get("collected_edges", 0),
            "graph_supernode_events": len(diag.get("supernode_events", [])),
            "flat_judge_rationale": jf["rationale"],
            "graph_judge_rationale": jg["rationale"],
        })
        traces[q.id] = {
            "question": q.question, "group": q.group,
            "reference_answer": q.reference_answer,
            "gold_evidence_chunks": sorted(gold_chunks),
            "flat_chunks": [
                {"chunk_id": r_.chunk_id, "score": round(float(r_.score), 3),
                 "date": str(r_.published_date), "text": r_.text[:600]}
                for r_ in flat["retrieved"].itertuples(index=False)],
            "graph_lines": graph["graph_debug"]["context"].splitlines()[:60],
            "graph_seeds": diag.get("matched_seeds", []),
            "graph_edges_sample": (graph_edges.head(60).to_dict("records") if len(graph_edges) else []),
            "flat_answer": flat["answer"], "graph_answer": graph["answer"],
            "judge_flat": jf, "judge_graph": jg,
            "flat_latency_s": round(flat["latency_s"], 3), "graph_latency_s": round(graph["latency_s"], 3),
            "flat_total_tokens": flat.get("total_tokens"), "graph_total_tokens": graph.get("total_tokens"),
        }
        pd.DataFrame(rows).to_csv(CHECKPOINT, index=False)
        json.dump(traces, open(TRACE_PATH, "w", encoding="utf-8"), ensure_ascii=False, indent=1)

    out = pd.DataFrame(rows)
    return out.set_index("id").loc[golden_df.id].reset_index()

validate_golden(golden_df, require_answers=True)
eval_results_df = run_evaluation(golden_df)
display(eval_results_df[["id", "group", "flat_comprehensiveness", "graph_comprehensiveness",
                         "flat_faithfulness", "graph_faithfulness",
                         "flat_multi_hop_reasoning", "graph_multi_hop_reasoning",
                         "flat_evidence_recall", "graph_evidence_recall"]])

Golden Dataset valid — du 3 nhom, khong con reference_answer trong.
[checkpoint] da co 25 cau -> chay tiep 0 cau

Evaluation: 0it [00:00, ?it/s]

Evaluation: 0it [00:00, ?it/s]

,id,group,flat_comprehensiveness,graph_comprehensiveness,flat_faithfulness,graph_faithfulness,flat_multi_hop_reasoning,graph_multi_hop_reasoning,flat_evidence_recall,graph_evidence_recall
0,G5000-26,multi-hop,5,5,5,5,5,5,1.000000,1.000000
1,G5000-27,cross-doc,3,4,3,3,2,3,1.000000,1.000000
2,G5000-28,multi-hop,5,3,5,2,5,5,1.000000,1.000000
3,G5000-29,cross-doc,5,5,5,5,5,5,1.000000,1.000000
4,G5000-30,multi-hop,2,2,2,3,2,1,0.500000,0.000000
5,G5000-31,multi-hop,3,5,4,5,3,5,0.750000,1.000000
6,G5000-32,cross-doc,4,5,3,5,2,5,0.500000,1.000000
7,G5000-33,cross-doc,3,2,2,2,2,1,0.500000,0.500000
8,G5000-34,multi-hop,2,4,2,4,1,4,0.666667,1.000000
9,G5000-35,cross-doc,4,5,3,5,2,5,0.500000,1.000000
10,G5000-36,cross-doc,4,4,3,4,2,3,0.500000,1.000000
11,G5000-37,cross-doc,5,5,5,5,5,5,1.000000,1.000000
12,G5000-38,multi-hop,4,5,4,2,3,3,1.000000,1.000000
13,G5000-39,multi-hop,5,5,5,5,5,5,1.000000,1.000000
14,G5000-40,cross-doc,2,4,2,3,1,3,0.500000,1.000000
15,G5000-41,factoid,5,5,5,5,5,5,1.000000,1.000000
16,G5000-42,multi-hop,5,5,5,5,5,5,1.000000,1.000000
17,G5000-43,cross-doc,2,5,2,5,1,5,0.500000,1.000000
18,G5000-44,multi-hop,5,5,5,5,5,5,0.333333,1.000000
19,G5000-45,cross-doc,3,4,4,4,2,3,1.000000,1.000000
20,G5000-46,cross-doc,5,5,5,5,5,5,1.000000,1.000000
21,G5000-47,factoid,5,5,5,5,5,5,1.000000,1.000000
22,G5000-48,multi-hop,5,5,5,5,5,5,1.000000,0.666667
23,G5000-49,multi-hop,2,4,2,3,2,4,0.333333,1.000000
24,G5000-50,multi-hop,3,3,3,2,2,3,0.666667,0.666667

In [21]:
#@title 4.4 — Comparison table + export
def comparison_table(eval_df):
    metric_map = {
        "Comprehensiveness":   ("flat_comprehensiveness", "graph_comprehensiveness"),
        "Faithfulness":        ("flat_faithfulness", "graph_faithfulness"),
        "Multi-hop reasoning": ("flat_multi_hop_reasoning", "graph_multi_hop_reasoning"),
        "Evidence recall":     ("flat_evidence_recall", "graph_evidence_recall"),
        "Latency (s)":         ("flat_latency_s", "graph_latency_s"),
        "Token usage":         ("flat_total_tokens", "graph_total_tokens"),
    }

    rows = []
    for group, g in list(eval_df.groupby("group")) + [("TOAN BO", eval_df)]:
        for metric, (fc, gc) in metric_map.items():
            f = pd.to_numeric(g[fc], errors="coerce").mean()
            gr = pd.to_numeric(g[gc], errors="coerce").mean()

            if metric in {"Latency (s)", "Token usage"}:
                ratio = gr / f if f else np.nan
                comment = (f"GraphRAG dat hon {ratio:.2f}x — gia phai tra cho graph context."
                           if gr > f else "GraphRAG khong dat hon trong sample nay.")
            elif metric == "Evidence recall":
                comment = (f"Hybrid lay ve {gr:.0%} chunk bang chung vang vs Flat {f:.0%}."
                           if gr >= f else "Flat retrieval trung bang chung tot hon — kiem tra seed matching.")
            else:
                delta = gr - f
                if delta >= .75:
                    comment = "GraphRAG cai thien ro; kiem tra rationale va provenance."
                elif delta <= -.5:
                    comment = "Flat RAG tot hon; graph extraction/retrieval co the gay mat thong tin hoac nhieu."
                else:
                    comment = "Hai phuong phap gan nhau."

            rows.append({
                "Loai cau hoi": group, "Metric": metric,
                "Flat RAG": round(f, 3) if pd.notna(f) else np.nan,
                "GraphRAG": round(gr, 3) if pd.notna(gr) else np.nan,
                "Delta": round(gr - f, 3) if pd.notna(f) and pd.notna(gr) else np.nan,
                "Nhan xet phan tich": comment,
            })
    return pd.DataFrame(rows)

comparison_df = comparison_table(eval_results_df)
display(comparison_df)

# README noi outputs/, RUBRIC muc 3.3 noi reports/ -> xuat ca hai, chi phi bang 0
eval_results_df.to_csv(OUT_DIR / "graphrag_eval_results.csv", index=False)
comparison_df.to_csv(OUT_DIR / "graphrag_vs_flatrag_summary.csv", index=False)
eval_results_df.to_csv(REP_DIR / "graphrag_eval_results.csv", index=False)
comparison_df.to_csv(REP_DIR / "graphrag_vs_flatrag_summary.csv", index=False)
print("Exported 2 CSV x 2 noi")

# --- Truy vet ca loi ngay luc chay (khong thi phai chay lai, ton token) ---
d = eval_results_df.copy()
for m in ["comprehensiveness", "faithfulness", "multi_hop_reasoning"]:
    d[f"delta_{m}"] = d[f"graph_{m}"] - d[f"flat_{m}"]
d["delta_total"] = d[[c for c in d.columns if c.startswith("delta_")]].sum(axis=1)
d.sort_values("delta_total", ascending=False).to_csv(OUT_DIR / "failure_case_ranking.csv", index=False)

print("\ndelta_total CAO nhat = ca Flat thua / Graph thang (muc 4.1 bao cao)")
print("delta_total THAP nhat = ca GraphRAG that bai   (muc 4.2 bao cao)")
display(d[["id", "group", "delta_total", "flat_evidence_recall", "graph_evidence_recall",
           "graph_matched_seeds", "graph_collected_edges"]].sort_values("delta_total"))

print("\n=== CA 1: Flat RAG that bai, GraphRAG thang ===")
best = d.sort_values("delta_total", ascending=False).iloc[0]
print(best.id, "|", best.group, "| delta:", best.delta_total)
print("Q:", best.question)
print("FLAT  :", best.flat_answer[:400])
print("GRAPH :", best.graph_answer[:400])
print("Judge flat :", best.flat_judge_rationale[:300])
print("Judge graph:", best.graph_judge_rationale[:300])

print("\n=== CA 2: GraphRAG kem hon / that bai ===")
worst = d.sort_values("delta_total").iloc[0]
print(worst.id, "|", worst.group, "| delta:", worst.delta_total)
print("Q:", worst.question)
print("FLAT  :", worst.flat_answer[:400])
print("GRAPH :", worst.graph_answer[:400])
print("seeds:", worst.graph_matched_seeds, "| edges:", worst.graph_collected_edges,
      "| graph-only evidence recall:", worst.graph_only_evidence_recall)
print("Judge graph:", worst.graph_judge_rationale[:300])

,Loai cau hoi,Metric,Flat RAG,GraphRAG,Delta,Nhan xet phan tich
0,cross-doc,Comprehensiveness,3.636,4.364,0.727,Hai phuong phap gan nhau.
1,cross-doc,Faithfulness,3.364,4.182,0.818,GraphRAG cai thien ro; kiem tra rationale va provenance.
2,cross-doc,Multi-hop reasoning,2.636,3.909,1.273,GraphRAG cai thien ro; kiem tra rationale va provenance.
3,cross-doc,Evidence recall,0.727,0.955,0.227,Hybrid lay ve 95% chunk bang chung vang vs Flat 73%.
4,cross-doc,Latency (s),2.262,2.105,-0.157,GraphRAG khong dat hon trong sample nay.
5,cross-doc,Token usage,681.182,1063.455,382.273,GraphRAG dat hon 1.56x — gia phai tra cho graph context.
6,factoid,Comprehensiveness,5.000,5.000,0.000,Hai phuong phap gan nhau.
7,factoid,Faithfulness,5.000,5.000,0.000,Hai phuong phap gan nhau.
8,factoid,Multi-hop reasoning,5.000,5.000,0.000,Hai phuong phap gan nhau.
9,factoid,Evidence recall,1.000,1.000,0.000,Hybrid lay ve 100% chunk bang chung vang vs Flat 100%.
10,factoid,Latency (s),1.246,1.860,0.614,GraphRAG dat hon 1.49x — gia phai tra cho graph context.
11,factoid,Token usage,718.500,931.000,212.500,GraphRAG dat hon 1.30x — gia phai tra cho graph context.
12,multi-hop,Comprehensiveness,3.833,4.250,0.417,Hai phuong phap gan nhau.
13,multi-hop,Faithfulness,3.917,3.833,-0.083,Hai phuong phap gan nhau.
14,multi-hop,Multi-hop reasoning,3.583,4.167,0.583,Hai phuong phap gan nhau.
15,multi-hop,Evidence recall,0.771,0.861,0.090,Hybrid lay ve 86% chunk bang chung vang vs Flat 77%.
16,multi-hop,Latency (s),2.330,2.266,-0.063,GraphRAG khong dat hon trong sample nay.
17,multi-hop,Token usage,712.667,1127.167,414.500,GraphRAG dat hon 1.58x — gia phai tra cho graph context.
18,TOAN BO,Comprehensiveness,3.840,4.360,0.520,Hai phuong phap gan nhau.
19,TOAN BO,Faithfulness,3.760,4.080,0.320,Hai phuong phap gan nhau.
20,TOAN BO,Multi-hop reasoning,3.280,4.120,0.840,GraphRAG cai thien ro; kiem tra rationale va provenance.
21,TOAN BO,Evidence recall,0.770,0.913,0.143,Hybrid lay ve 91% chunk bang chung vang vs Flat 77%.
22,TOAN BO,Latency (s),2.213,2.163,-0.051,GraphRAG khong dat hon trong sample nay.
23,TOAN BO,Token usage,699.280,1083.440,384.160,GraphRAG dat hon 1.55x — gia phai tra cho graph context.

Exported 2 CSV x 2 noi

delta_total CAO nhat = ca Flat thua / Graph thang (muc 4.1 bao cao)
delta_total THAP nhat = ca GraphRAG that bai   (muc 4.2 bao cao)

,id,group,delta_total,flat_evidence_recall,graph_evidence_recall,graph_matched_seeds,graph_collected_edges
2,G5000-28,multi-hop,-5,1.000000,1.000000,Google Cloud|Google Cloud,6
7,G5000-33,cross-doc,-2,0.500000,0.500000,OpenAI,8
12,G5000-38,multi-hop,-1,1.000000,1.000000,Dell Technologies|cloud services|Dell NativeEdge,15
3,G5000-29,cross-doc,0,1.000000,1.000000,NaN,0
4,G5000-30,multi-hop,0,0.500000,0.000000,Meta,3
13,G5000-39,multi-hop,0,1.000000,1.000000,Hewlett Packard Enterprise|Axis Security|H2O AI Cloud,4
11,G5000-37,cross-doc,0,1.000000,1.000000,Dell Technologies|Dell NativeEdge,3
0,G5000-26,multi-hop,0,1.000000,1.000000,Amazon|Artificial Intelligence,20
15,G5000-41,factoid,0,1.000000,1.000000,Hewlett Packard Enterprise,2
21,G5000-47,factoid,0,1.000000,1.000000,Keysight|Synopsys|Palo Alto Networks,10
24,G5000-50,multi-hop,0,0.666667,0.666667,NVIDIA|AMD|Intel|Artificial Intelligence,11
22,G5000-48,multi-hop,0,1.000000,0.666667,Snowflake|Artificial Intelligence,4
20,G5000-46,cross-doc,0,1.000000,1.000000,Keysight|Synopsys|Palo Alto Networks,10
16,G5000-42,multi-hop,0,1.000000,1.000000,Dell Technologies|Hewlett Packard Enterprise,3
18,G5000-44,multi-hop,0,0.333333,1.000000,L&T Technology Services,12
10,G5000-36,cross-doc,2,0.500000,1.000000,Amazon|Artificial Intelligence,20
19,G5000-45,cross-doc,2,1.000000,1.000000,L&T Technology Services|Qualcomm|Thales,12
1,G5000-27,cross-doc,2,1.000000,1.000000,AMD|AWS|Advanced Micro Devices AI chips,9
5,G5000-31,multi-hop,5,0.750000,1.000000,OpenAI|open-source language model|AI software marketplace,8
14,G5000-40,cross-doc,5,0.500000,1.000000,Dell Technologies|Hewlett Packard Enterprise|Microsoft Azure,26
23,G5000-49,multi-hop,5,0.333333,1.000000,Samsung|GIS Technology,10
6,G5000-32,cross-doc,6,0.500000,1.000000,OpenAI,8
9,G5000-35,cross-doc,6,0.500000,1.000000,AWS|Hewlett Packard Enterprise|AI cloud services,5
8,G5000-34,multi-hop,7,0.666667,1.000000,Google Cloud|Amazon|Artificial Intelligence,25
17,G5000-43,cross-doc,10,0.500000,1.000000,Hewlett Packard Enterprise|Axis Security,2

=== CA 1: Flat RAG that bai, GraphRAG thang ===
G5000-43 | cross-doc | delta: 10
Q: Which came first in the selected HPE timeline: the Axis Security acquisition agreement or the LLM-focused cloud service announcement, and what does that ordering show?
FLAT  : The Axis Security acquisition agreement came first on March 2, 2023, while the LLM-focused cloud service announcement is not explicitly mentioned in the provided context. Therefore, it is unclear when the LLM-focused cloud service was announced. The ordering of the acquisition suggests that HPE is prioritizing the enhancement of its security capabilities before expanding into new cloud services, i
GRAPH : The Axis Security acquisition agreement came first on March 2, 2023, followed by the announcement of the LLM-focused cloud service on June 21, 2023. This ordering shows that HPE prioritized strengthening its security capabilities through acquisition before expanding its cloud service offerings for artificial intelligence, indicating a strategic focus on security as a foundational element for its c
Judge flat : The candidate answer correctly identifies the date of the Axis Security acquisition but fails to provide the date for the LLM-focused cloud service announcement, which is crucial for comprehensiveness. It also makes unsupported claims about HPE's strategic focus without evidence from the context. Th
Judge graph: The candidate answer accurately states the dates of both events and their order, matching the reference answer. It also correctly interprets the significance of this ordering, indicating a strategic focus on security before cloud services. All claims are supported by the provided context.

=== CA 2: GraphRAG kem hon / that bai ===
G5000-28 | multi-hop | delta: -5
Q: Which model providers are connected to Google Cloud Next '23 in the selected data, and which models are associated with each provider?
FLAT  : The model providers connected to Google Cloud Next '23 are:

1. **Meta**:
   - Models: Llama 2 and Code Llama

2. **Technology Innovative Institute**:
   - Model: Falcon LLM

3. **Anthropic**:
   - Model: Claude 2 (pre-announced)

Google Cloud will uniquely offer both adapter tuning and RLHF for Llama 2 [chunk_id=row03395::c0000].
GRAPH : The model providers connected to Google Cloud Next '23 and their associated models are:

1. **Meta** - Code Llama
2. **Anthropic** - Claude 2
3. **Technology Innovative Institute** - Falcon LLM
4. **Google** - Llama 2

These models were announced or pre-announced during the event on August 29, 2023 [chunk_id=row03395::c0000].
seeds: Google Cloud|Google Cloud | edges: 6 | graph-only evidence recall: 1.0
Judge graph: The candidate answer covers most of the model providers and their associated models but misses Meta's Llama 2, which is a significant omission. The claim about Google being connected to Llama 2 is unsupported by the context provided, as it states that Llama 2 is from Meta. The reasoning hops are cor

# PHẦN 5 — FAILURE-MODE CHECKS & SUBMISSION (105–120')

Bắt buộc chứng minh:
1. Edge provenance không thiếu.
2. Entity Resolution có audit.
3. Super-node degree > 100 chỉ expand tối đa 50 edge.
4. Có comparison table.

In [22]:
#@title 5.1 — Super-node check + entity audit
supernode_proof = {}

def test_supernode_policy():
    rows = run_cypher("""
    MATCH (n:Entity)-[r]-()
    WITH n, count(r) AS degree
    ORDER BY degree DESC LIMIT 1
    RETURN n.id AS id, n.name AS name, degree
    """)
    if not rows:
        print("Graph empty.")
        return None

    n = rows[0]
    limit = SUPER_NODE_EDGE_CAP if n["degree"] > SUPER_NODE_DEGREE else 1000
    edges = recent_edges(n["id"], limit)
    print(n, "fetched=", len(edges))
    if n["degree"] > SUPER_NODE_DEGREE:
        assert len(edges) <= SUPER_NODE_EDGE_CAP
        print("Super-node cap OK (degree that > 100).")
    return n

def show_resolution_audit(audit_df):
    if audit_df.empty:
        print("No audit rows.")
        return
    display(audit_df.sort_values("similarity", ascending=False).head(30))
    print("Cac cap similarity cao NHUNG bi Lexical Guard chan:")
    display(audit_df[audit_df.decision == "REJECT_GUARD"]
            .sort_values("similarity", ascending=False).head(20))

top_node = test_supernode_policy()

# BAY LON NHAT cua bai lab: o scale 400 chunk, max degree thuong < 100 -> nhanh assert khong bao gio
# chay -> khong co bang chung nao du code dung. Ha nguong TAM THOI de KIEM CHUNG co che hoat dong.
top = top_degree_df.iloc[0]
supernode_proof = {"top_name": str(top["name"]), "real_degree": int(top.degree),
                   "production_threshold": SUPER_NODE_DEGREE, "edge_cap": SUPER_NODE_EDGE_CAP}

if int(top.degree) <= SUPER_NODE_DEGREE:
    _old = SUPER_NODE_DEGREE
    SUPER_NODE_DEGREE = max(1, int(top.degree) - 1)
    try:
        g = retrieve_graph_context(f"Tell me everything about {top['name']}",
                                   max_hops=2, edge_limit=200, return_debug=True)
        ev = g["diagnostics"]["supernode_events"]
        print("degree that:", int(top.degree), "| nguong test:", SUPER_NODE_DEGREE)
        print("supernode_events:", ev)
        print("edges thu duoc:", g["diagnostics"]["collected_edges"])
        assert ev and all(e["limit"] <= SUPER_NODE_EDGE_CAP for e in ev), "Cap KHONG duoc ap dung!"
        print("Super-node cap hoat dong: moi event bi chan o", SUPER_NODE_EDGE_CAP)
        supernode_proof.update({"test_threshold": int(SUPER_NODE_DEGREE),
                                "events": ev,
                                "edges_collected": int(g["diagnostics"]["collected_edges"]),
                                "mode": "ha nguong tam thoi de kiem chung"})
    finally:
        SUPER_NODE_DEGREE = _old
        print("Da khoi phuc SUPER_NODE_DEGREE =", SUPER_NODE_DEGREE)
else:
    supernode_proof.update({"mode": "super-node co that trong graph"})

# Kiem tra tran toan cuc GLOBAL_EDGE_CAP
_g = retrieve_graph_context(f"Tell me everything about {top['name']}",
                            max_hops=3, edge_limit=200, return_debug=True)
print("Hop=3, edge_limit=200 ->", _g["diagnostics"]["collected_edges"],
      "edges (GLOBAL_EDGE_CAP =", GLOBAL_EDGE_CAP, ")")
assert _g["diagnostics"]["collected_edges"] <= GLOBAL_EDGE_CAP
print("Do dai graph context:", len(_g["context"]), "ky tu (tran =", MAX_GRAPH_CONTEXT_CHARS, ")")
assert len(_g["context"]) <= MAX_GRAPH_CONTEXT_CHARS
supernode_proof["global_cap_check"] = {"edges": int(_g["diagnostics"]["collected_edges"]),
                                       "cap": GLOBAL_EDGE_CAP,
                                       "context_chars": len(_g["context"])}

display(top_degree_df.head(10))
show_resolution_audit(entity_resolution_audit_df)

# Bang chung "similarity cao nhung KHONG merge" (cau thuyet minh #2)
high_reject = (entity_resolution_audit_df
               .query("decision=='REJECT_GUARD' and similarity > 0.85")
               .sort_values("similarity", ascending=False).head(10))
display(high_reject)

{'id': 'fb0f4df56fab164ec48722f0', 'name': 'Microsoft', 'degree': 21} fetched= 21

degree that: 21 | nguong test: 20
supernode_events: [{'node_id': 'fb0f4df56fab164ec48722f0', 'degree': 21, 'limit': 50}]
edges thu duoc: 31
Super-node cap hoat dong: moi event bi chan o 50
Da khoi phuc SUPER_NODE_DEGREE = 100

Hop=3, edge_limit=200 -> 52 edges (GLOBAL_EDGE_CAP = 250 )
Do dai graph context: 11484 ky tu (tran = 14000 )

                         id                     name        type  degree
0  fb0f4df56fab164ec48722f0                Microsoft     Company      21
1  68b3544368862fc263941c8d                   Amazon     Company      12
2  7b29988cfc0dac3059f47a0e  L&T Technology Services     Company       7
3  cc9c6ee3857729e221d3f6de               ServiceNow     Company       7
4  70c4e949ff245096c6946802      Amazon Web Services     Company       7
5  110cfb16be66531da841ce26                   Thales     Company       6
6  4a992388a70cd573ed2b4d6b                    Falco  Technology       5
7  261c78e541bbb8921217639a                 Qualcomm     Company       5
8  0e132222d1315530d6efca52                   Google     Company       5
9  773eeb9b7cc008bff365fcdd                   OpenAI     Company       5

,type,left,right,similarity,decision,lexical_ratio
0,Company,HPE,Hewlett Packard Enterprise,1.000000,MERGE_MANUAL,NaN
1,Company,Dell,Dell Technologies,1.000000,MERGE_MANUAL,NaN
2,Company,Meta Platforms Inc,Meta,1.000000,MERGE_MANUAL,NaN
8,Company,Cumulus Technology Services Inc,Cumulus Technology Services Inc.,0.994372,MERGE_VECTOR,1.000
5,Company,Amazon Web Services,Amazon Web Services (AWS),0.928739,MERGE_VECTOR,0.905
3,Company,L&T Technology Services Limited,L&T Technology Services,0.925773,MERGE_VECTOR,1.000
7,Company,Synergy Quantum,Synergy Quantum India,0.867454,REJECT_THRESHOLD,0.833
14,Technology,generative AI,Generative AI Solutions,0.866633,REJECT_THRESHOLD,0.722
15,Technology,generative AI,Generative AI Capabilities,0.856484,REJECT_THRESHOLD,0.667
4,Company,Synopsys,Synopsys Inc.,0.832365,REJECT_THRESHOLD,1.000
10,Technology,cloud computing,cloud services,0.830391,REJECT_THRESHOLD,0.483
6,Company,Amazon Web Services,Amazon Web Services Inc.,0.823628,REJECT_THRESHOLD,1.000
21,Technology,Now Assist Generative AI Capabilities,Generative AI Capabilities,0.796372,REJECT_THRESHOLD,0.825
11,Technology,Llama 2,Code Llama,0.783534,REJECT_THRESHOLD,0.588
19,Technology,generative AI solutions for manufacturing,Generative AI Solutions,0.781076,REJECT_THRESHOLD,0.719
12,Technology,ChatGPT,OpenAI's ChatGPT,0.773496,REJECT_THRESHOLD,0.609
22,Technology,SAP CRM Sales,SAP CRM Service Manager,0.773034,REJECT_THRESHOLD,0.611
20,Technology,Generative AI Solutions,Generative AI Capabilities,0.773009,REJECT_THRESHOLD,0.735
16,Technology,generative AI,Generative AI offerings,0.766575,REJECT_THRESHOLD,0.722
17,Technology,Generative AI offerings,Generative AI Capabilities,0.759788,REJECT_THRESHOLD,0.653
9,Company,Broadridge Financial Solutions,Broadridge,0.754731,REJECT_THRESHOLD,0.500
13,Technology,Climate Innovation Fund,Climate Pledge Fund,0.752083,REJECT_THRESHOLD,0.619
18,Technology,Generative AI offerings,Generative AI Solutions,0.751441,REJECT_THRESHOLD,0.783

Cac cap similarity cao NHUNG bi Lexical Guard chan:

Empty DataFrame
Columns: [type, left, right, similarity, decision, lexical_ratio]
Index: []

Empty DataFrame
Columns: [type, left, right, similarity, decision, lexical_ratio]
Index: []

## 5.2 — Thuyết minh kỹ thuật: học viên tự điền

1. Coreference sai ở tình huống nào?
2. Entity threshold bao nhiêu, vì sao?
3. Candidate nào similarity cao nhưng không nên merge?
4. Top 3 super-node và degree?
5. Vì sao ưu tiên edge mới nhất có thể đúng/sai?
6. Flat RAG thắng nhóm nào?
7. GraphRAG thắng nhóm nào?
8. Latency/token trade-off?
9. AI Coding Agent đề xuất gì mà bạn **không dùng**, vì sao?
10. Scale 350MB: bottleneck đầu tiên là gì?

# 🎁 BONUS

## A — Low-level / High-level
Tạo local entities và high-level topics/community reports; query router chọn tầng retrieval.

## B — Global Search via Community Reports
Nếu Neo4j instance không có GDS phù hợp, fallback:
1. export edges,
2. NetworkX community detection,
3. `UNWIND` write `community_id`,
4. LLM summarize community,
5. query global trên reports.

## C — Self-Correction Graph Retrieval
- hop 2 → LLM kiểm tra context đủ chưa,
- thiếu → hop 3,
- vẫn thiếu → vector fallback,
- bắt buộc stop condition.

In [23]:
#@title Bonus B (+5) — Global Search qua Community Detection (NetworkX)
import networkx as nx

def build_communities(limit_edges=20000):
    edge_df = pd.DataFrame(run_cypher("""
    MATCH (a:Entity)-[r]->(b:Entity)
    RETURN a.id AS source, b.id AS target
    LIMIT $limit
    """, limit=int(limit_edges)))

    G = nx.Graph()
    G.add_edges_from(edge_df[["source", "target"]].itertuples(index=False, name=None))
    communities = nx.algorithms.community.greedy_modularity_communities(G)

    rows = []
    for cid, members in enumerate(communities):
        rows += [{"id": node_id, "community_id": int(cid)} for node_id in members]

    for b in batches(rows, 1000):
        run_cypher("""
        UNWIND $rows AS row
        MATCH (n:Entity {id:row.id})
        SET n.community_id=row.community_id
        """, rows=b)
    return pd.DataFrame(rows), G

community_df, G_nx = build_communities()
print("communities:", community_df.community_id.nunique(), "| nodes gan cong dong:", len(community_df))

# Sinh "community report" cho cac cong dong lon nhat (dung cho global search)
def community_report(cid, max_edges=40):
    edges = run_cypher("""
    MATCH (a:Entity {community_id:$cid})-[r]->(b:Entity)
    RETURN a.name AS src, type(r) AS rel, b.name AS dst,
           r.published_date AS date, r.source_chunk_id AS chunk
    ORDER BY coalesce(r.published_date,'') DESC LIMIT $lim
    """, cid=int(cid), lim=int(max_edges))
    if not edges:
        return None
    facts = "\n".join(f"{e['src']} -{e['rel']}-> {e['dst']} | {e['date']} | {e['chunk']}" for e in edges)
    obj, _ = gen_json(
        "You summarise a knowledge-graph community for global search. Return strict JSON only.",
        f"""Community facts:
{facts}

Return json: {{"title":"short theme name","summary":"3-4 sentences on what this community is about",
"key_entities":["..."]}}""")
    return {"community_id": int(cid), "title": obj.get("title", ""),
            "summary": norm_space(obj.get("summary", "")),
            "key_entities": ", ".join(obj.get("key_entities", [])[:8]),
            "n_edges": len(edges)}

top_communities = community_df.community_id.value_counts().head(5).index.tolist()
community_reports = [r for r in (community_report(c) for c in top_communities) if r]
community_reports_df = pd.DataFrame(community_reports)
display(community_reports_df)
community_reports_df.to_csv(OUT_DIR / "community_reports.csv", index=False)

# Global question: cau hoi vi mo ma ca Flat RAG lan local GraphRAG deu tra loi kem
GLOBAL_Q = "What are the main themes of AI competition among big tech companies in this news corpus?"
global_ctx = "\n\n".join(
    f"[community {r['community_id']} | {r['title']} | {r['n_edges']} edges]\n{r['summary']}\nKey entities: {r['key_entities']}"
    for r in community_reports)

global_answer = generate_answer(GLOBAL_Q, global_ctx)
local_answer = answer_graph_rag(GLOBAL_Q)
print("=" * 25, "GLOBAL SEARCH (community reports)", "=" * 25)
print(global_answer["answer"][:900])
print("=" * 25, "LOCAL GRAPHRAG (seed + BFS)", "=" * 25)
print(local_answer["answer"][:900])
print("\nSo sanh chi phi: global tokens =", global_answer["total_tokens"],
      "| local hybrid tokens =", local_answer["total_tokens"])

communities: 145 | nodes gan cong dong: 393

,community_id,title,summary,key_entities,n_edges
0,0,Microsoft and AI Innovations,"This community focuses on Microsoft's advancements in artificial intelligence and cloud computing, highlighting its ...","Microsoft, SAP, KPMG, Dell Technologies Inc., Satya Nadella",27
1,1,AI and Cloud Innovations,This community focuses on the development and utilization of advanced AI technologies and cloud services by major te...,"Google, Amazon, IBM, Bard AI, Gemini, Cohere, Falco, DataCenter",21
2,2,Technology Partnerships in Telecommunications and Security,"This community focuses on strategic partnerships among technology companies, particularly in the fields of telecommu...","L&T Technology Services, Thales, Qualcomm, Palo Alto Networks, Ansys, Airbus, MTM Technology, Campina Grande's City ...",12
3,3,Amazon Web Services Community,"The Amazon Web Services (AWS) community is centered around the cloud computing platform provided by Amazon, which of...","Amazon Web Services, Olivia Igbokwe-Curry, Hugging Face, Cerro Coso Community College, eCloudvalley, Advanced Micro ...",7
4,4,Samsung and Partners in Smart Technology,This community focuses on the collaborations and innovations involving Samsung and its partners in the smart technol...,"Samsung, Aqara, FP2 Presence Sensor, SmartThings Platform, OLED display with embedded heart rate sensor, CDW, First Tee",8

========================= GLOBAL SEARCH (community reports) =========================
The main themes of AI competition among big tech companies in the news corpus include:

1. **Strategic Partnerships**: Companies like Microsoft, Google, and Amazon are forming partnerships to enhance their AI capabilities and expand market reach. For instance, Microsoft collaborates with SAP and KPMG, while Amazon partners with Hugging Face and educational institutions to innovate in AI and cloud services [community 0 | community 1 | community 3].

2. **Cloud Computing Leadership**: There is a strong emphasis on cloud technology as a foundation for AI advancements. Microsoft and Amazon are highlighted for their cloud services, with Microsoft’s Azure OpenAI Service and Amazon Web Services (AWS) being key players in the AI landscape [community 0 | community 1 | community 3].

3. **Generative AI Innovations**: The development of generative AI models, such as Google's Bard AI and Gemini, is
========================= LOCAL GRAPHRAG (seed + BFS) =========================
The main themes of AI competition among big tech companies in the provided context include:

1. **Impact on Industry and Society**: AI is reshaping the technology industry and its relationship with the public, indicating a significant transformation in products and services due to AI advancements [chunk_id=row01473::c0000].

2. **Risk Management and Accountability**: Tech giants are engaging with the government to address the risks associated with AI, including commitments to security testing and transparency about known risks [chunk_id=row02615::c0000][chunk_id=row03380::c0000]. However, there are concerns about the lack of accountability in these processes.

3. **Job Creation and Automation**: The rise of generative AI is leading to new job opportunities in technology, particularly in sectors like financial services, as automation becomes more prevalent [chunk_id=row00485::c0000].

Th

So sanh chi phi: global tokens = 1001 | local hybrid tokens = 602

In [24]:
#@title Bonus C (+5) — Self-Correction Retrieval (hop2 -> hop3 -> vector fallback)
SUFFICIENCY_SYSTEM = """
Decide whether the supplied retrieval context is sufficient to answer the question faithfully.
Do not answer the question. Return strict JSON only.
""".strip()

def context_sufficient(question, context):
    obj, _ = gen_json(
        SUFFICIENCY_SYSTEM,
        f"""QUESTION: {question}
CONTEXT:
{context[:16000]}
Return json {{"sufficient": true, "missing": "..."}}""")
    return bool(obj.get("sufficient")), norm_space(obj.get("missing"))

def self_correcting_context(question):
    g2 = retrieve_graph_context(question, 2, 50, True)
    ok, missing = context_sufficient(question, g2["context"])
    if ok:
        return {"route": "hop2", "context": g2["context"], "missing": "",
                "edges": g2["diagnostics"]["collected_edges"], "debug": g2}

    g3 = retrieve_graph_context(question, 3, 50, True)
    ok, missing2 = context_sufficient(question, g3["context"])
    if ok:
        return {"route": "hop3", "context": g3["context"], "missing": missing,
                "edges": g3["diagnostics"]["collected_edges"], "debug": g3}

    flat, _ = retrieve_flat_context(question, k=8)
    return {"route": "hop3+vector",
            "context": f"=== GRAPH ===\n{g3['context']}\n\n=== VECTOR ===\n{flat}",
            "missing": missing2, "edges": g3["diagnostics"]["collected_edges"], "debug": g3}

# Do DINH LUONG truoc/sau tren 3 cau multi-hop kho nhat (graph score thap nhat)
mh = eval_results_df[eval_results_df.group.isin(["multi-hop", "cross-doc"])].copy()
mh["graph_score"] = mh[["graph_comprehensiveness", "graph_faithfulness", "graph_multi_hop_reasoning"]].sum(axis=1)
targets = mh.sort_values("graph_score").head(3)

sc_rows = []
for r in targets.itertuples(index=False):
    base_edges = int(r.graph_collected_edges)
    sc = self_correcting_context(r.question)
    ans = generate_answer(r.question, sc["context"])
    j = judge_answer(r.question, r.reference_answer, ans["answer"], sc["context"])
    sc_rows.append({
        "id": r.id, "group": r.group, "route": sc["route"],
        "edges_truoc(hop2)": base_edges, "edges_sau": sc["edges"],
        "missing_detected": sc["missing"][:120],
        "judge_truoc": int(r.graph_comprehensiveness + r.graph_faithfulness + r.graph_multi_hop_reasoning),
        "judge_sau": j["comprehensiveness"] + j["faithfulness"] + j["multi_hop_reasoning"],
        "answer_sau": ans["answer"][:300],
    })

self_correction_df = pd.DataFrame(sc_rows)
self_correction_df["delta_judge"] = self_correction_df.judge_sau - self_correction_df.judge_truoc
display(self_correction_df[["id", "group", "route", "edges_truoc(hop2)", "edges_sau",
                            "judge_truoc", "judge_sau", "delta_judge", "missing_detected"]])
self_correction_df.to_csv(OUT_DIR / "self_correction_results.csv", index=False)
print("Tong diem judge thay doi:", int(self_correction_df.delta_judge.sum()))

,id,group,route,edges_truoc(hop2),edges_sau,judge_truoc,judge_sau,delta_judge,missing_detected
0,G5000-33,cross-doc,hop2,8,8,5,5,0,
1,G5000-30,multi-hop,hop2,3,3,6,3,-3,
2,G5000-50,multi-hop,hop3+vector,11,11,8,10,2,"The context does not provide specific information about the AI positioning of NVIDIA, AMD, and Intel, nor does it re..."

Tong diem judge thay doi: -1

In [25]:
#@title Bonus A (+3) — Near-dedup bang MinHash + LSH (thay vi chi exact SHA-1)
# Exact dedup chi bat duoc ban sao BYTE-IDENTICAL. Tin tuc syndicated (Reuters -> Indian Express)
# viet lai tieu de vai tu -> hash khac nhau -> cung 1 su kien duoc dem 2 lan trong graph
# (vd hang 2532 vs 2537 trong Golden G5000-36). MinHash+LSH bat duoc lop trung lap nay
# voi chi phi O(N * num_perm) thay vi O(N^2) cosine tren toan corpus.
NUM_PERM, BANDS, SHINGLE = 96, 24, 5     # 24 band x 4 row -> nguong Jaccard hieu dung ~0.72

def shingles(text, k=SHINGLE):
    toks = re.sub(r"[^a-z0-9 ]", " ", norm_space(text).lower()).split()
    if len(toks) <= k:
        return {" ".join(toks)} if toks else set()
    return {" ".join(toks[i:i+k]) for i in range(len(toks)-k+1)}

def minhash_signature(text, perms):
    sh = shingles(text)
    if not sh:
        return np.full(NUM_PERM, np.iinfo(np.uint64).max, dtype=np.uint64)
    h = np.array([int(hashlib.sha1(s.encode()).hexdigest()[:15], 16) for s in sh], dtype=np.uint64)
    a, b = perms
    M = np.uint64(2**61 - 1)
    return ((a[:, None] * h[None, :] + b[:, None]) % M).min(axis=1)

rng = np.random.default_rng(SEED)
perms = (rng.integers(1, 2**61-1, NUM_PERM, dtype=np.uint64),
         rng.integers(0, 2**61-1, NUM_PERM, dtype=np.uint64))

t0 = time.perf_counter()
sigs = np.vstack([minhash_signature(t, perms) for t in tqdm(chunks_df.text, desc="MinHash")])
rows_per_band = NUM_PERM // BANDS

buckets = defaultdict(list)
for band in range(BANDS):
    sl = sigs[:, band*rows_per_band:(band+1)*rows_per_band]
    for i, key in enumerate(map(lambda r: hashlib.sha1(r.tobytes()).hexdigest(), sl)):
        buckets[(band, key)].append(i)

def jaccard(i, j):
    return float((sigs[i] == sigs[j]).mean())

uf_nd = UF(len(chunks_df))
pairs = []
seen_pair = set()
for members in buckets.values():
    if len(members) < 2 or len(members) > 50:
        continue
    for x in range(len(members)):
        for y in range(x+1, len(members)):
            i, j = members[x], members[y]
            if (i, j) in seen_pair:
                continue
            seen_pair.add((i, j))
            sim = jaccard(i, j)
            if sim >= 0.72:
                uf_nd.union(i, j)
                pairs.append({"i": i, "j": j, "jaccard_est": round(sim, 3),
                              "title_i": chunks_df.title.iloc[i][:70],
                              "title_j": chunks_df.title.iloc[j][:70]})

groups_nd = defaultdict(list)
for i in range(len(chunks_df)):
    groups_nd[uf_nd.find(i)].append(i)
dupe_clusters = {k: v for k, v in groups_nd.items() if len(v) > 1}
n_removed = sum(len(v) - 1 for v in dupe_clusters.values())

near_dup_pairs_df = pd.DataFrame(pairs).sort_values("jaccard_est", ascending=False) if pairs else pd.DataFrame()
print(f"MinHash+LSH tren {len(chunks_df):,} chunk trong {time.perf_counter()-t0:.1f}s "
      f"({len(seen_pair):,} cap duoc so sanh thay vi {len(chunks_df)*(len(chunks_df)-1)//2:,} cap O(N^2))")
print(f"Cum trung lap gan: {len(dupe_clusters)} | so chunk se bi loai them: {n_removed} "
      f"({n_removed/len(chunks_df):.2%} corpus)")
display(near_dup_pairs_df.head(15))
if len(near_dup_pairs_df):
    near_dup_pairs_df.to_csv(OUT_DIR / "near_duplicate_pairs.csv", index=False)

dedup_summary_df = pd.DataFrame([
    {"buoc": "Raw 5.000 dong dau",           "so_ban_ghi": len(raw_first5000)},
    {"buoc": "Sau loc snippet >=120 ky tu",  "so_ban_ghi": len(raw_df)},
    {"buoc": "Sau exact dedup (SHA-1)",      "so_ban_ghi": len(news_df)},
    {"buoc": "Sau near-dedup (MinHash/LSH)", "so_ban_ghi": len(chunks_df) - n_removed},
])
display(dedup_summary_df)
dedup_summary_df.to_csv(OUT_DIR / "dedup_summary.csv", index=False)

MinHash:   0%|          | 0/2114 [00:00<?, ?it/s]

MinHash:  27%|██▋       | 578/2114 [00:00<00:00, 5772.59it/s]

MinHash:  55%|█████▍    | 1156/2114 [00:00<00:00, 5316.07it/s]

MinHash:  81%|████████  | 1706/2114 [00:00<00:00, 5380.80it/s]

MinHash: 100%|██████████| 2114/2114 [00:00<00:00, 5257.33it/s]

MinHash+LSH tren 2,114 chunk trong 0.6s (358 cap duoc so sanh thay vi 2,233,441 cap O(N^2))
Cum trung lap gan: 22 | so chunk se bi loai them: 24 (1.14% corpus)

,i,j,jaccard_est,title_i,title_j
1,185,689,1.000,Sensormatic Solutions by Johnson Controls shares 2022 U.S. Super Satur,Sensormatic Solutions by Johnson Controls shares 2022 U.S. Super Satur
3,496,1873,1.000,CereCore® expands healthcare technology services into the UK,CereCore expands healthcare technology services into the UK
8,1221,1486,1.000,411 is going out of service for millions of Americans,411 is going out of service for millions of Americans
7,932,1421,0.958,Why Operators Need a Full-Service Technology Partner,Restaurant Tech: Why Operators Need a Full-Service Technology Partner
11,1337,1824,0.958,411 phone number is going out of service for millions of Americans,411 is going out of service for millions of Americans
19,1576,1676,0.854,Stock market today: Wall Street is mixed; Big Tech climbs,Stock market today: Wall Street is mixed; Big Tech climbs
17,788,1557,0.854,Fidelity National Information Services (FIS) Stock Moves -0.9%: What Y,Fidelity National Information Services (FIS) Stock Moves -0.9%: What Y
0,21,888,0.833,Samsung Showcases Groundbreaking Logic Innovations at System LSI Tech,Samsung Showcases Groundbreaking Logic Innovations at System LSI Tech
15,439,1452,0.833,Degrees & Pathways,Human Services Technology: Addiction and Recovery Studies AAS
21,214,714,0.833,Yonyou Auto Information Technology (Shanghai) Co. Ltd.,Information Services Group Inc.
5,737,1758,0.823,US announces criminal cases involving flow of technology information t,US Announces Criminal Cases Involving Flow of Technology Information t
14,426,767,0.812,Alight launches new behavioral health navigation services aimed at sup,Alight launches new behavioral health navigation services aimed at sup
13,473,1580,0.802,L T Technology Services and Qualcomm Selected by Thales for Enabling 5,L&T Technology Services and Qualcomm Selected by Thales for Enabling 5
10,1317,1843,0.792,Best VoIP Services (July 2023),Best VoIP Services (October 2023)
2,468,533,0.792,Information Services Group Inc. (NASDAQ:III) is a favorite amongst ins,Information Services Group Inc. (NASDAQ:III) is a favorite amongst ins

                           buoc  so_ban_ghi
0            Raw 5.000 dong dau        5000
1   Sau loc snippet >=120 ky tu        2687
2       Sau exact dedup (SHA-1)        2114
3  Sau near-dedup (MinHash/LSH)        2090

# 📦 PHAN 6 — Xuat du lieu cho Demo UI

Cell duoi dong goi toan bo bang chung (pipeline stats, subgraph, ket qua eval, trace retrieval)
thanh `outputs/demo_data.json` de giao dien demo `demo/index.html` doc truc tiep.
File nay **khong chua secret** — chi so lieu, cau tra loi, subgraph va trace retrieval.

In [26]:
#@title 6.1 — Xuat du lieu cho Demo UI (outputs/demo_data.json)
# Dong goi toan bo bang chung cua lab thanh 1 file JSON de UI demo (demo/index.html) doc.
# KHONG chua secret — chi so lieu, cau tra loi, subgraph va trace retrieval.
def jsonable(obj):
    if isinstance(obj, (np.integer,)):
        return int(obj)
    if isinstance(obj, (np.floating,)):
        return None if pd.isna(obj) else float(obj)
    if isinstance(obj, (np.bool_,)):
        return bool(obj)
    return obj

def df_records(df, n=None):
    d = df.head(n) if n else df
    return json.loads(d.to_json(orient="records"))

graph_nodes = run_cypher("""
MATCH (n:Entity)
OPTIONAL MATCH (n)-[r]-()
WITH n, count(r) AS degree
RETURN n.id AS id, n.name AS name, n.entity_type AS type, degree,
       coalesce(n.community_id, -1) AS community_id
ORDER BY degree DESC LIMIT 400
""")
keep_ids = {n["id"] for n in graph_nodes}
graph_edges_all = run_cypher("""
MATCH (a:Entity)-[r]->(b:Entity)
RETURN a.id AS source, a.name AS source_name, a.entity_type AS source_type,
       type(r) AS relation,
       b.id AS target, b.name AS target_name, b.entity_type AS target_type,
       r.published_date AS date, r.source_chunk_id AS chunk,
       r.confidence AS confidence, left(coalesce(r.evidence,''), 220) AS evidence
ORDER BY coalesce(r.published_date,'') DESC LIMIT 1200
""")
graph_edges_view = [e for e in graph_edges_all if e["source"] in keep_ids and e["target"] in keep_ids]

demo_payload = {
    "meta": {
        "generated_at": time.strftime("%Y-%m-%d %H:%M:%S"),
        "extraction_model": GROQ_MODEL,
        "judge_model": f"{JUDGE_PROVIDER}/{JUDGE_MODEL}",
        "embedding_model": EMBED_MODEL,
        "dataset": "HackerNoon/tech-company-news-data-dump (5.000 dong dau)",
    },
    "pipeline": {
        "raw_rows": int(len(raw_first5000)),
        "after_length_filter": int(len(raw_df)),
        "articles_after_exact_dedup": int(len(news_df)),
        "chunks": int(len(chunks_df)),
        "near_dup_removable": int(n_removed),
        "extraction_chunks": int(len(extraction_source)),
        "coref_changed_chunks": int(len(changed)),
        "raw_triples": int(len(raw_triples_df)),
        "triples_after_er": int(len(triples_df)),
        "nodes": int(len(nodes_df)),
        "edges_in_graph": int(graph_counts["edges"]),
        "invalid_provenance_edges": int(graph_counts["invalid_provenance_edges"]),
        "relation_distribution": {k: int(v) for k, v in triples_df.relation.value_counts().items()},
        "node_type_distribution": {k: int(v) for k, v in nodes_df.type.value_counts().items()},
        "communities": int(community_df.community_id.nunique()) if "community_df" in dir() else 0,
    },
    "graph": {"nodes": graph_nodes, "edges": graph_edges_view},
    "top_degree": df_records(top_degree_df, 15),
    "entity_audit": df_records(entity_resolution_audit_df.sort_values("similarity", ascending=False), 60),
    "threshold_sweep": df_records(threshold_sweep_df),
    "guard_probe": df_records(guard_probe_df),
    "eval_results": df_records(eval_results_df),
    "comparison": df_records(comparison_df),
    "traces": json.load(open(str(OUT_DIR / "eval_traces.json"), encoding="utf-8")),
    "self_correction": df_records(self_correction_df),
    "community_reports": df_records(community_reports_df),
    "dedup_summary": df_records(dedup_summary_df),
    "near_dup_pairs": df_records(near_dup_pairs_df, 20) if len(near_dup_pairs_df) else [],
    "supernode_demo": supernode_proof,
}

# Thong ke chi phi LLM cua PHIEN HIEN TAI (cac buoc lay tu cache khong goi LLM nen khong xuat hien).
llm_cost_df = llm_cost_summary()
if len(llm_cost_df):
    display(llm_cost_df)
    llm_cost_df.to_csv(OUT_DIR / "llm_cost_summary.csv", index=False)
    demo_payload["llm_cost"] = df_records(llm_cost_df)
    print("Tong token phien nay:", int(llm_cost_df.tokens.sum()))

demo_path = OUT_DIR / "demo_data.json"
json.dump(demo_payload, open(demo_path, "w", encoding="utf-8"), ensure_ascii=False, default=jsonable)
print("Da xuat", demo_path, f"({demo_path.stat().st_size/1e6:.2f} MB)")
print("Khoa co trong payload:", list(demo_payload.keys()))

      tag provider        model  calls  tokens  latency_s  retries
0  answer   openai  gpt-4o-mini      7    5551      16.81        0
1     gen   openai  gpt-4o-mini      9    5223      15.23        0
2    seed   openai  gpt-4o-mini     10    1392      15.34        0

Tong token phien nay: 12166
Da xuat d:\VINUNI\d19\K4-Track3-Lab19-GraphRAG-2A202601748-DuongNgocHai\outputs\demo_data.json (0.56 MB)
Khoa co trong payload: ['meta', 'pipeline', 'graph', 'top_degree', 'entity_audit', 'threshold_sweep', 'guard_probe', 'eval_results', 'comparison', 'traces', 'self_correction', 'community_reports', 'dedup_summary', 'near_dup_pairs', 'supernode_demo', 'llm_cost']

# ✅ RUBRIC

- **30% Chạy được code:** graph nạp thành công, schema đúng, xuất bảng.
- **30% Failure modes:** xử lý ít nhất 2/3 vấn đề Super-node, Entity Resolution, Coreference.
- **20% Evaluation:** chạy hết Golden Dataset, phân tích hợp lý.
- **20% Thuyết minh:** giải thích kiến trúc và cách kiểm soát AI Coding Agent.

## Submission checklist
- [ ] Neo4j connected
- [ ] Dedup/chunking đã chạy
- [ ] Coreference spot-check
- [ ] Entity resolution audit
- [ ] `UNWIND` bulk insert
- [ ] 0 edge thiếu provenance
- [ ] Flat RAG chạy
- [ ] GraphRAG chạy
- [ ] Super-node check
- [ ] Golden Dataset có gold answers thật
- [ ] Evaluation chạy hết
- [ ] Export results + summary CSV
- [ ] Thuyết minh kỹ thuật
- [ ] Bonus (nếu có) có định lượng trước/sau